const std = @import("std");
const diff_mod = @import("../diff/engine.zig");
const ast_mod = @import("../types/ast.zig");
const resolved_ast = @import("../types/resolved_ast.zig");
const codegen = @import("../codegen/codegen.zig");
const typed_ast = @import("../types/typed_ast.zig");
const dialect_mod = @import("../dialect/dialect.zig");
const dialect_enum = @import("../dialect/enum.zig");
const TypeResolver = @import("../types/type_resolver.zig").TypeResolver;
const utils = @import("../utils.zig");
const emit = @import("../diff/emit.zig");
const version = @import("../version.zig");
const helpers = @import("migrate_helpers.zig");
const Field = ast_mod.Field;
const TypeInfo = ast_mod.TypeInfo;

const Dialect = dialect_enum.Dialect;

// ─── Direction ────────────────────────────────────────────────

/// Controls whether emission targets forward migration or rollback.
const Direction = enum { forward, rollback };

// ─── Helpers ───────────────────────────────────────────────

const optionalStrEq = utils.optionalStrEq;
const emitSingleTable = helpers.emitSingleTable;

// ─── generateFromDiff (orchestrator) ─────────────────────────

/// Generate forward migration SQL from a SchemaDiff. Outputs ALTER TABLE statements
/// wrapped in a BEGIN/COMMIT transaction.
pub fn generateFromDiff(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    new_typed: typed_ast.TypedAst,
    new_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Migration: schema diff\n");
    try w.print("-- Generated by rune {s} migrate\n\n", .{version.VERSION});
    try w.writeAll("BEGIN;\n\n");

    var has_operations = false;

    try emitDroppedTables(w, dialect_mod.getBackend(dialect), d.dropped_tables);
    if (d.dropped_tables.len > 0) has_operations = true;

    try emitViewDiffs(w, dialect_mod.getBackend(dialect), d.view_diffs, new_typed);
    if (d.view_diffs.len > 0) has_operations = true;

    var cg = codegen.Codegen.init(alloc, dialect);
    try emitTableDiffs(alloc, w, d.table_diffs, new_resolved, dialect, &cg, &has_operations);

    try w.writeAll("COMMIT;\n");

    try w.flush();
    return try aw.toOwnedSlice();
}

// ─── Rollback Generation ─────────────────────────────────────

/// Generate rollback SQL from a SchemaDiff. Outputs the inverse operations
/// (re-create dropped tables, reverse ALTER TABLE changes) wrapped in BEGIN/COMMIT.
pub fn generateRollback(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    old_typed: typed_ast.TypedAst,
    old_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Rollback: undo migration\n");
    try w.print("-- Generated by rune {s} migrate --rollback\n\n", .{version.VERSION});
    try w.writeAll("BEGIN;\n\n");

    var has_operations = false;

    // Rollback: reverse the order of operations
    // 1. Reverse table diffs (create→drop, drop→create, alter→reverse alter)
    var cg = codegen.Codegen.init(alloc, dialect);
    try emitTableDiffs(alloc, w, d.table_diffs, old_resolved, dialect, &cg, &has_operations);

    // 2. Reverse view diffs
    try emitViewDiffs(w, dialect_mod.getBackend(dialect), d.view_diffs, old_typed);

    // 3. Reverse dropped tables (they become CREATE in rollback)
    try emitRollbackDroppedTables(alloc, w, d.dropped_tables, old_resolved, dialect, &has_operations);

    try w.writeAll("COMMIT;\n");

    try w.flush();
    return try aw.toOwnedSlice();
}

// ─── Shared Emission Functions ──────────────────────────────────

fn emitDroppedTables(w: anytype, backend: dialect_mod.DialectBackend, dropped: []const []const u8) !void {
    for (dropped) |tname| {
        try w.writeAll("DROP TABLE IF EXISTS ");
        try backend.quoteIdent(w, tname);
        try w.writeAll(";\n\n");
    }
}

fn emitViewDiffs(w: anytype, backend: dialect_mod.DialectBackend, view_diffs: []const diff_mod.ViewDiff, typed: typed_ast.TypedAst) !void {
    for (view_diffs) |vd| {
        switch (vd.action) {
            .drop => {
                try w.writeAll("DROP VIEW IF EXISTS ");
                try backend.quoteIdent(w, vd.name);
                try w.writeAll(";\n\n");
            },
            .create, .modify => {
                if (vd.action == .modify) {
                    try w.writeAll("DROP VIEW IF EXISTS ");
                    try backend.quoteIdent(w, vd.name);
                    try w.writeAll(";\n\n");
                }
                if (emit.findTypedView(typed, vd.name)) |view| {
                    try backend.emitCreateView(w, view.name, view.query);
                    try w.writeAll("\n");
                }
            },
        }
    }
}

fn emitTableDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    table_diffs: []const diff_mod.TableDiff,
    resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
    cg: ?*codegen.Codegen,
    has_operations: *bool,
) !void {
    const backend = dialect_mod.getBackend(dialect);

    for (table_diffs) |td| {
        switch (td.action) {
            .create => {
                if (cg) |c| {
                    has_operations.* = true;
                    try emitSingleTable(alloc, w, c, resolved, td.name, dialect);
                }
            },
            .alter => {
                var table_has_ops = false;
                var sub_needs_comma = false;

                try emitFieldDiffs(alloc, w, backend, td, cg, dialect, resolved, &table_has_ops, &sub_needs_comma);
                try emitIndexDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);
                try emitMetadataDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);
                try emitFkDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);

                if (table_has_ops) {
                    has_operations.* = true;
                    try w.writeAll(";\n");
                }
            },
        }
    }
}

fn emitFieldDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    cg: ?*codegen.Codegen,
    dialect: Dialect,
    resolved: resolved_ast.ResolvedAst,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.field_diffs) |fd| {
        switch (fd.action) {
            .add => try emitAddField(alloc, w, backend, td.name, fd, cg, dialect, resolved, table_has_ops, sub_needs_comma),
            .drop => try emitDropField(w, backend, td.name, fd, table_has_ops, sub_needs_comma),
            .modify => try emitModifyField(alloc, w, backend, td.name, fd, cg, dialect, resolved, table_has_ops, sub_needs_comma),
            .rename => try emitRenameField(alloc, w, backend, td.name, fd, cg, dialect, resolved, table_has_ops, sub_needs_comma),
        }
    }
}

fn emitAddField(
    alloc: std.mem.Allocator,
    w: anytype,
    backend: dialect_mod.DialectBackend,
    table_name: []const u8,
    fd: diff_mod.FieldDiff,
    cg: ?*codegen.Codegen,
    dialect: Dialect,
    resolved: resolved_ast.ResolvedAst,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    if (cg) |c| {
        try emit.beginAlterTable(w, backend, table_name, table_has_ops);
        const field_to_use = if (fd.new_field) |nf| nf else if (fd.old_field) |of| of else return;
        try emit.emitComma(w, sub_needs_comma);
        try w.writeAll("ADD COLUMN ");
        const typed_col = try TypeResolver.resolveColumn(alloc, field_to_use, dialect, resolved.custom_types);
        try c.emitColumnDef(w, typed_col);
    }
}

fn emitDropField(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    table_name: []const u8,
    fd: diff_mod.FieldDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    try emit.beginAlterTable(w, backend, table_name, table_has_ops);
    try emit.emitComma(w, sub_needs_comma);
    try backend.emitAlterDropColumn(w, fd.name);
}

fn emitModifyField(
    alloc: std.mem.Allocator,
    w: anytype,
    backend: dialect_mod.DialectBackend,
    table_name: []const u8,
    fd: diff_mod.FieldDiff,
    cg: ?*codegen.Codegen,
    dialect: Dialect,
    resolved: resolved_ast.ResolvedAst,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    try emit.beginAlterTable(w, backend, table_name, table_has_ops);
    const field_to_use = if (fd.new_field) |nf| nf else if (fd.old_field) |of| of else return;
    try emit.emitComma(w, sub_needs_comma);
    try backend.emitAlterModifyColumn(w, field_to_use.name);
    if (backend.modify_needs_column_def) {
        const typed_col = try TypeResolver.resolveColumn(alloc, field_to_use, dialect, resolved.custom_types);
        if (cg) |c| {
            try c.emitColumnDefEx(w, typed_col, backend.modify_column_def_skips_name);
        }
    }
}

fn emitRenameField(
    alloc: std.mem.Allocator,
    w: anytype,
    backend: dialect_mod.DialectBackend,
    table_name: []const u8,
    fd: diff_mod.FieldDiff,
    cg: ?*codegen.Codegen,
    dialect: Dialect,
    resolved: resolved_ast.ResolvedAst,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    try emit.beginAlterTable(w, backend, table_name, table_has_ops);
    if (fd.rename_from) |old_name| {
        try emit.emitComma(w, sub_needs_comma);
        try backend.emitAlterRenameColumn(w, old_name, fd.name);
        if (backend.rename_needs_column_def) {
            const field_to_use = if (fd.new_field) |nf| nf else if (fd.old_field) |of| of else return;
            if (cg) |c| {
                const typed_col = try TypeResolver.resolveColumn(alloc, field_to_use, dialect, resolved.custom_types);
                try c.emitColumnDef(w, typed_col);
            }
        }
    }
}

fn emitIndexDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.index_diffs) |idx_diff| {
        switch (idx_diff.action) {
            .add => {
                if (idx_diff.new_idx) |idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, idx);
                }
            },
            .drop => {
                if (idx_diff.old_idx) |idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, idx);
                }
            },
            .modify => {
                // Forward: drop old, add new; Rollback: drop new, add old
                const drop_idx = if (idx_diff.old_idx) |old_idx| old_idx else null;
                const add_idx = if (idx_diff.new_idx) |new_idx| new_idx else null;
                if (drop_idx) |di| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, di);
                }
                if (add_idx) |ai| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, ai);
                }
            },
        }
    }
}

fn emitMetadataDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    if (td.metadata_diff) |md| {
        if (!optionalStrEq(md.old_comment, md.new_comment)) {
            const comment = md.new_comment;
            if (comment) |c| {
                const result = backend.commentResult();
                switch (result) {
                    .added_to_alter => {
                        try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                        try emit.emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, c);
                    },
                    .standalone_emitted => {
                        if (table_has_ops.*) {
                            try w.writeAll(";\n\n");
                            table_has_ops.* = false;
                            sub_needs_comma.* = false;
                        }
                        try backend.emitAlterTableComment(w, td.name, c);
                    },
                    .unsupported => {
                        try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                        try emit.emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, c);
                    },
                }
            }
        }
        if (!optionalStrEq(md.old_engine, md.new_engine)) {
            try emit.beginAlterTable(w, backend, td.name, table_has_ops);
            try emit.emitComma(w, sub_needs_comma);
            try backend.emitAlterEngine(w, md.new_engine);
        }
    }
}

fn emitFkDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.fk_diffs) |fk_diff| {
        switch (fk_diff.action) {
            .add => {
                if (fk_diff.new_fk) |fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, fk);
                }
            },
            .drop => {
                if (fk_diff.old_fk) |fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, fk);
                }
            },
            .modify => {
                // Forward: drop old, add new; Rollback: drop new, add old
                const drop_fk = if (fk_diff.old_fk) |old_fk| old_fk else null;
                const add_fk = if (fk_diff.new_fk) |new_fk| new_fk else null;
                if (drop_fk) |df| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, df);
                }
                if (add_fk) |af| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, af);
                }
            },
        }
    }
}

// ─── Rollback-specific helpers ────────────────────────────────

fn emitRollbackDroppedTables(
    alloc: std.mem.Allocator,
    w: anytype,
    dropped: []const []const u8,
    old_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
    has_operations: *bool,
) !void {
    var cg = codegen.Codegen.init(alloc, dialect);
    for (dropped) |tname| {
        has_operations.* = true;
        try emitSingleTable(alloc, w, &cg, old_resolved, tname, dialect);
    }
}
