const std = @import("std");
const diff_mod = @import("../diff/engine.zig");
const ast_mod = @import("../types/ast.zig");
const resolved_ast = @import("../types/resolved_ast.zig");
const codegen = @import("../codegen/codegen.zig");
const typed_ast = @import("../types/typed_ast.zig");
const dialect_mod = @import("../dialect/dialect.zig");
const dialect_enum = @import("../dialect/enum.zig");
const TypeResolver = @import("../types/type_resolver.zig").TypeResolver;
const utils = @import("../utils.zig");
const emit = @import("../diff/emit.zig");
const version = @import("../version.zig");
const helpers = @import("migrate_helpers.zig");
const Field = ast_mod.Field;
const TypeInfo = ast_mod.TypeInfo;

const Dialect = dialect_enum.Dialect;

// ─── Helpers ───────────────────────────────────────────────

const optionalStrEq = utils.optionalStrEq;
const emitSingleTable = helpers.emitSingleTable;

// ─── generateFromDiff (orchestrator) ─────────────────────────

/// Generate forward migration SQL from a SchemaDiff. Outputs ALTER TABLE statements
/// wrapped in a BEGIN/COMMIT transaction.
pub fn generateFromDiff(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    new_typed: typed_ast.TypedAst,
    new_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Migration: schema diff\n");
    try w.print("-- Generated by rune {s} migrate\n\n", .{version.VERSION});
    try w.writeAll("BEGIN;\n\n");

    var has_operations = false;

    try emitDroppedTables(w, dialect_mod.getBackend(dialect), d.dropped_tables);
    if (d.dropped_tables.len > 0) has_operations = true;

    try emitViewDiffs(w, dialect_mod.getBackend(dialect), d.view_diffs, new_typed);
    if (d.view_diffs.len > 0) has_operations = true;

    var cg = codegen.Codegen.init(alloc, dialect);
    try emitTableDiffs(alloc, w, d.table_diffs, new_resolved, dialect, &cg, &has_operations);

    try w.writeAll("COMMIT;\n");

    try w.flush();
    return try aw.toOwnedSlice();
}

// ─── Rollback Generation ─────────────────────────────────────

/// Generate rollback SQL from a SchemaDiff. Outputs the inverse operations
/// (re-create dropped tables, reverse ALTER TABLE changes) wrapped in BEGIN/COMMIT.
pub fn generateRollback(
    alloc: std.mem.Allocator,
    d: diff_mod.SchemaDiff,
    old_typed: typed_ast.TypedAst,
    old_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.writeAll("-- Rollback: undo migration\n");
    try w.print("-- Generated by rune {s} migrate --rollback\n\n", .{version.VERSION});
    try w.writeAll("BEGIN;\n\n");

    var has_operations = false;

    // Rollback: reverse the order of operations
    // 1. Reverse table diffs (create→drop, drop→create, alter→reverse alter)
    try emitRollbackTableDiffs(alloc, w, d.table_diffs, old_resolved, dialect, &has_operations);

    // 2. Reverse view diffs
    try emitRollbackViewDiffs(w, d.view_diffs, old_typed, dialect, &has_operations);

    // 3. Reverse dropped tables (they become CREATE in rollback)
    try emitRollbackDroppedTables(alloc, w, d.dropped_tables, old_resolved, dialect, &has_operations);

    try w.writeAll("COMMIT;\n");

    try w.flush();
    return try aw.toOwnedSlice();
}

fn emitRollbackDroppedTables(
    alloc: std.mem.Allocator,
    w: anytype,
    dropped: []const []const u8,
    old_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
    has_operations: *bool,
) !void {
    var cg = codegen.Codegen.init(alloc, dialect);
    for (dropped) |tname| {
        has_operations.* = true;
        try emitSingleTable(alloc, w, &cg, old_resolved, tname, dialect);
    }
}

fn emitRollbackViewDiffs(
    w: anytype,
    view_diffs: []const diff_mod.ViewDiff,
    old_typed: typed_ast.TypedAst,
    dialect: Dialect,
    has_operations: *bool,
) !void {
    for (view_diffs) |vd| {
        const backend = dialect_mod.getBackend(dialect);
        switch (vd.action) {
            .create => {
                // Rollback create → drop
                has_operations.* = true;
                try w.writeAll("DROP VIEW IF EXISTS ");
                try backend.quoteIdent(w, vd.name);
                try w.writeAll(";\n\n");
            },
            .drop => {
                // Rollback drop → recreate from old schema
                has_operations.* = true;
                if (emit.findTypedView(old_typed, vd.name)) |view| {
                    try backend.emitCreateView(w, view.name, view.query);
                    try w.writeAll("\n");
                }
            },
            .modify => {
                // Rollback modify → recreate from old schema
                has_operations.* = true;
                try w.writeAll("DROP VIEW IF EXISTS ");
                try backend.quoteIdent(w, vd.name);
                try w.writeAll(";\n\n");
                if (emit.findTypedView(old_typed, vd.name)) |view| {
                    try backend.emitCreateView(w, view.name, view.query);
                    try w.writeAll("\n");
                }
            },
        }
    }
}

fn emitRollbackTableDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    table_diffs: []const diff_mod.TableDiff,
    old_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
    has_operations: *bool,
) !void {
    const backend = dialect_mod.getBackend(dialect);

    for (table_diffs) |td| {
        switch (td.action) {
            .create => {
                // Rollback create → drop
                has_operations.* = true;
                try w.writeAll("DROP TABLE IF EXISTS ");
                try backend.quoteIdent(w, td.name);
                try w.writeAll(";\n\n");
            },
            .alter => {
                var table_has_ops = false;
                var sub_needs_comma = false;

                // Rollback field diffs in reverse
                try emitRollbackFieldDiffs(alloc, w, backend, td, old_resolved, dialect, &table_has_ops, &sub_needs_comma);
                // Rollback index diffs in reverse
                try emitRollbackIndexDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);
                // Rollback metadata diffs (restore old comment/engine)
                try emitRollbackMetadataDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);
                // Rollback FK diffs in reverse
                try emitRollbackFkDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);

                if (table_has_ops) {
                    has_operations.* = true;
                    try w.writeAll(";\n");
                }
            },
        }
    }
}

fn emitRollbackFieldDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    old_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    var cg = codegen.Codegen.init(alloc, dialect);
    for (td.field_diffs) |fd| {
        switch (fd.action) {
            .add => {
                // Rollback add → drop
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                try emit.emitComma(w, sub_needs_comma);
                try backend.emitAlterDropColumn(w, fd.name);
            },
            .drop => {
                // Rollback drop → add (use old field definition)
                if (fd.old_field) |of| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD COLUMN ");
                    const typed_col = try TypeResolver.resolveColumn(alloc, of, dialect, old_resolved.custom_types);
                    try cg.emitColumnDef(w, typed_col);
                }
            },
            .modify => {
                // Rollback modify → restore old column definition
                if (fd.old_field) |of| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterModifyColumn(w, of.name);
                    if (backend.modify_needs_column_def) {
                        const typed_col = try TypeResolver.resolveColumn(alloc, of, dialect, old_resolved.custom_types);
                        try cg.emitColumnDefEx(w, typed_col, backend.modify_column_def_skips_name);
                    }
                }
            },
            .rename => {
                // Rollback rename → rename back to old name
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.rename_from) |old_name| {
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterRenameColumn(w, fd.name, old_name);
                    if (backend.rename_needs_column_def) {
                        if (fd.old_field) |of| {
                            const typed_col = try TypeResolver.resolveColumn(alloc, of, dialect, old_resolved.custom_types);
                            try cg.emitColumnDef(w, typed_col);
                        }
                    }
                }
            },
        }
    }
}

fn emitRollbackIndexDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.index_diffs) |idx_diff| {
        switch (idx_diff.action) {
            .add => {
                // Rollback add → drop
                if (idx_diff.new_idx) |idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, idx);
                }
            },
            .drop => {
                // Rollback drop → add old index
                if (idx_diff.old_idx) |idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, idx);
                }
            },
            .modify => {
                // Rollback modify → restore old, drop new
                if (idx_diff.new_idx) |new_idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, new_idx);
                }
                if (idx_diff.old_idx) |old_idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, old_idx);
                }
            },
        }
    }
}

fn emitRollbackFkDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.fk_diffs) |fk_diff| {
        switch (fk_diff.action) {
            .add => {
                // Rollback add → drop
                if (fk_diff.new_fk) |fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, fk);
                }
            },
            .drop => {
                // Rollback drop → add old FK
                if (fk_diff.old_fk) |fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, fk);
                }
            },
            .modify => {
                // Rollback modify → drop new, add old
                if (fk_diff.new_fk) |new_fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, new_fk);
                }
                if (fk_diff.old_fk) |old_fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, old_fk);
                }
            },
        }
    }
}

fn emitRollbackMetadataDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    if (td.metadata_diff) |md| {
        // Rollback comment: restore old comment
        if (!optionalStrEq(md.old_comment, md.new_comment)) {
            if (md.old_comment) |oc| {
                const result = backend.commentResult();
                switch (result) {
                    .added_to_alter => {
                        try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                        try emit.emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, oc);
                    },
                    .standalone_emitted => {
                        if (table_has_ops.*) {
                            try w.writeAll(";\n\n");
                            table_has_ops.* = false;
                            sub_needs_comma.* = false;
                        }
                        try backend.emitAlterTableComment(w, td.name, oc);
                    },
                    .unsupported => {
                        try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                        try emit.emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, oc);
                    },
                }
            }
        }
        // Rollback engine: restore old engine
        if (!optionalStrEq(md.old_engine, md.new_engine)) {
            if (md.old_engine) |oe| {
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                try emit.emitComma(w, sub_needs_comma);
                try backend.emitAlterEngine(w, oe);
            }
        }
    }
}

// ─── generateFromDiff sub-functions ────────────────────────────

fn emitDroppedTables(w: anytype, backend: dialect_mod.DialectBackend, dropped: []const []const u8) !void {
    for (dropped) |tname| {
        try w.writeAll("DROP TABLE IF EXISTS ");
        try backend.quoteIdent(w, tname);
        try w.writeAll(";\n\n");
    }
}

fn emitViewDiffs(w: anytype, backend: dialect_mod.DialectBackend, view_diffs: []const diff_mod.ViewDiff, new_typed: typed_ast.TypedAst) !void {
    for (view_diffs) |vd| {
        switch (vd.action) {
            .drop => {
                try w.writeAll("DROP VIEW IF EXISTS ");
                try backend.quoteIdent(w, vd.name);
                try w.writeAll(";\n\n");
            },
            .create, .modify => {
                if (vd.action == .modify) {
                    try w.writeAll("DROP VIEW IF EXISTS ");
                    try backend.quoteIdent(w, vd.name);
                    try w.writeAll(";\n\n");
                }
                if (emit.findTypedView(new_typed, vd.name)) |view| {
                    try backend.emitCreateView(w, view.name, view.query);
                    try w.writeAll("\n");
                }
            },
        }
    }
}

fn emitTableDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    table_diffs: []const diff_mod.TableDiff,
    new_resolved: resolved_ast.ResolvedAst,
    dialect: Dialect,
    cg: *codegen.Codegen,
    has_operations: *bool,
) !void {
    const backend = dialect_mod.getBackend(dialect);

    for (table_diffs) |td| {
        switch (td.action) {
            .create => {
                has_operations.* = true;
                try emitSingleTable(alloc, w, cg, new_resolved, td.name, dialect);
            },
            .alter => {
                var table_has_ops = false;
                var sub_needs_comma = false;

                try emitFieldDiffs(alloc, w, backend, td, cg, dialect, new_resolved, &table_has_ops, &sub_needs_comma);
                try emitIndexDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);
                try emitMetadataDiffs(w, backend, td, &table_has_ops, &sub_needs_comma, has_operations);
                try emitFkDiffs(w, backend, td, &table_has_ops, &sub_needs_comma);

                if (table_has_ops) {
                    has_operations.* = true;
                    try w.writeAll(";\n");
                }
            },
        }
    }
}

fn emitFieldDiffs(
    alloc: std.mem.Allocator,
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    cg: *codegen.Codegen,
    dialect: Dialect,
    new_resolved: resolved_ast.ResolvedAst,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.field_diffs) |fd| {
        switch (fd.action) {
            .add => {
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.new_field) |nf| {
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD COLUMN ");
                    const typed_col = try TypeResolver.resolveColumn(alloc, nf, dialect, new_resolved.custom_types);
                    try cg.emitColumnDef(w, typed_col);
                }
            },
            .drop => {
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                try emit.emitComma(w, sub_needs_comma);
                try backend.emitAlterDropColumn(w, fd.name);
            },
            .modify => {
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.new_field) |nf| {
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterModifyColumn(w, nf.name);
                    if (backend.modify_needs_column_def) {
                        const typed_col = try TypeResolver.resolveColumn(alloc, nf, dialect, new_resolved.custom_types);
                        try cg.emitColumnDefEx(w, typed_col, backend.modify_column_def_skips_name);
                    }
                }
            },
            .rename => {
                try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                if (fd.rename_from) |old_name| {
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterRenameColumn(w, old_name, fd.name);
                    if (backend.rename_needs_column_def) {
                        if (fd.new_field) |nf| {
                            const typed_col = try TypeResolver.resolveColumn(alloc, nf, dialect, new_resolved.custom_types);
                            try cg.emitColumnDef(w, typed_col);
                        }
                    }
                }
            },
        }
    }
}

fn emitIndexDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.index_diffs) |idx_diff| {
        switch (idx_diff.action) {
            .add => {
                if (idx_diff.new_idx) |idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, idx);
                }
            },
            .drop => {
                if (idx_diff.old_idx) |idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, idx);
                }
            },
            .modify => {
                if (idx_diff.old_idx) |old_idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropIndex(w, old_idx);
                }
                if (idx_diff.new_idx) |new_idx| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterAddIndex(w, td.name, new_idx);
                }
            },
        }
    }
}

fn emitMetadataDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
    has_operations: *bool,
) !void {
    if (td.metadata_diff) |md| {
        if (!optionalStrEq(md.old_comment, md.new_comment)) {
            if (md.new_comment) |nc| {
                const result = backend.commentResult();
                switch (result) {
                    .added_to_alter => {
                        try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                        try emit.emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, nc);
                    },
                    .standalone_emitted => {
                        if (table_has_ops.*) {
                            try w.writeAll(";\n\n");
                            table_has_ops.* = false;
                            sub_needs_comma.* = false;
                        }
                        try backend.emitAlterTableComment(w, td.name, nc);
                        has_operations.* = true;
                    },
                    .unsupported => {
                        try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                        try emit.emitComma(w, sub_needs_comma);
                        try backend.emitAlterTableComment(w, td.name, nc);
                    },
                }
            }
        }
        if (!optionalStrEq(md.old_engine, md.new_engine)) {
            try emit.beginAlterTable(w, backend, td.name, table_has_ops);
            try emit.emitComma(w, sub_needs_comma);
            try backend.emitAlterEngine(w, md.new_engine);
        }
    }
}

fn emitFkDiffs(
    w: anytype,
    backend: dialect_mod.DialectBackend,
    td: diff_mod.TableDiff,
    table_has_ops: *bool,
    sub_needs_comma: *bool,
) !void {
    for (td.fk_diffs) |fk_diff| {
        switch (fk_diff.action) {
            .add => {
                if (fk_diff.new_fk) |fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, fk);
                }
            },
            .drop => {
                if (fk_diff.old_fk) |fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, fk);
                }
            },
            .modify => {
                if (fk_diff.old_fk) |old_fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try backend.emitAlterDropFk(w, old_fk);
                }
                if (fk_diff.new_fk) |new_fk| {
                    try emit.beginAlterTable(w, backend, td.name, table_has_ops);
                    try emit.emitComma(w, sub_needs_comma);
                    try w.writeAll("ADD ");
                    try backend.emitForeignKey(w, new_fk);
                }
            },
        }
    }
}
