#!/bin/bash
# ── Rune Test Library ──
# Shared functions for all test runners.
# Source this file: source "$(dirname "$0")/lib.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# rune.exe is a native Windows binary: it cannot see MSYS virtual paths
# (/e/..., /tmp/...). Convert once; all suites inherit these.
if command -v cygpath >/dev/null 2>&1; then
  SCRIPT_DIR=$(cygpath -m "$SCRIPT_DIR")
  PROJECT_DIR=$(cygpath -m "$PROJECT_DIR")
fi

# Detect binary name: .exe on Windows/MSYS, plain name on Linux/macOS
if [[ "$OSTYPE" == msys* || "$OSTYPE" == cygwin* || "$OSTYPE" == win32 ]]; then
  BIN_SUFFIX=".exe"
else
  BIN_SUFFIX=""
fi
COMPILER="$PROJECT_DIR/rune/zig-out/bin/rune${BIN_SUFFIX}"

# Ensure compiler exists
if [ ! -f "$COMPILER" ]; then
  echo "ERROR: Compiler not found at $COMPILER"
  echo "Run 'cd rune && zig build' first."
  exit 1
fi

PASS=0
FAIL=0
SKIP=0
ERRORS=""

pass() {
  printf "  \033[32m✅\033[0m %s\n" "$1"
  PASS=$((PASS + 1))
}

fail() {
  printf "  \033[31m❌\033[0m %s\n" "$1"
  if [ -n "${2:-}" ]; then
    printf "     \033[90m%s\033[0m\n" "$2"
  fi
  FAIL=$((FAIL + 1))
  ERRORS="$ERRORS $1"
}

skip() {
  printf "  \033[33m⏭\033[0m  %s  (%s)\n" "$1" "${2:-skipped}"
  SKIP=$((SKIP + 1))
}

header() {
  echo ""
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
  printf "\033[1m%s\033[0m\n" "$1"
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
  echo ""
}

summary() {
  local label="${1:-Tests}"
  local total=$((PASS + FAIL))
  echo ""
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
  if [ $FAIL -eq 0 ]; then
    printf "\033[32m%s: %d/%d passed\033[0m\n" "$label" "$PASS" "$total"
  else
    printf "\033[31m%s: %d/%d passed, %d failed\033[0m\n" "$label" "$PASS" "$total" "$FAIL"
  fi
  if [ $SKIP -gt 0 ]; then
    printf "\033[33m  (%d skipped)\033[0m\n" "$SKIP"
  fi
  if [ -n "$ERRORS" ]; then
    printf "\033[31mFailed:%s\033[0m\n" "$ERRORS"
  fi
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
}

# Strip the "Generated by rune X.Y.Z" version comment from SQL output.
# This makes golden tests resilient to version bumps.
strip_version() {
  grep -v '^-- Generated by rune ' || true
}

# Strip version from JSON output (removes "version": "X.Y.Z" line).
strip_version_json() {
  grep -v '"version": "[0-9]' || true
}

# Strip version from any output (auto-detect format).
# For SQL: strips "-- Generated by rune" comment lines.
# For JSON: strips lines containing "version": "X.Y.Z".
strip_version_auto() {
  local first_line
  first_line=$(head -1 "$1" 2>/dev/null || true)
  if [[ "$first_line" == "# Generated by rune "* ]]; then
    # GraphQL/hashtag comment format
    grep -v '^# Generated by rune ' || true
  elif [[ "$first_line" == "{"* ]] || [[ "$first_line" == "  {"* ]]; then
    # JSON format
    grep -v '"version": "[0-9]' || true
  else
    # SQL format (default)
    strip_version
  fi
}

# Compare two files ignoring version strings.
# Usage: compare_files <expected> <actual>
# Returns 0 if identical (ignoring version), 1 if different.
# Single awk process — on Windows/MSYS each forked process costs ~20-30ms,
# and this runs once per golden test case (hundreds per suite).
compare_files() {
  local expected="$1" actual="$2"
  awk '
    NR==FNR {
      sub(/\r$/, "")
      if ($0 !~ /^-- Generated by rune / && $0 !~ /^# Generated by rune / && $0 !~ /"version": "[0-9]/)
        exp_lines[++n] = $0
      next
    }
    {
      sub(/\r$/, "")
      if ($0 !~ /^-- Generated by rune / && $0 !~ /^# Generated by rune / && $0 !~ /"version": "[0-9]/) {
        c++
        if (c > n || $0 != exp_lines[c]) exit 1
      }
    }
    END { if (c != n) exit 1 }
  ' "$expected" "$actual"
}

# ── Parallel golden-suite engine ─────────────────────────────
# Compiles all eligible .ss test files via ONE `rune compile-batch` process
# (manifest: input<TAB>output<TAB>dialect), then diffs each output against
# expected/<base><suffix> with CASE_JOBS concurrent awk workers.
#
# Rationale: on Windows/MSYS a rune.exe spawn costs ~0.15s while the compile
# itself is ~5ms — per-case invocation was ~92% process overhead. One batch
# process removes it; diffs are cheap and parallelize across cores.
#
# Usage: run_golden_cases <suite_label> <dialect|"" for default> <golden_suffix> <skip_regex>
#   skip_regex — ERE of base-name prefixes to exclude (e.g. '^(sqlite-|migrate-)')
run_golden_cases() {
  local label="$1" dialect="$2" suffix="$3" skip_re="${4:-}" include_re="${5:-}"
  local filter="${FILTER:-}"
  local jobs="${CASE_JOBS:-6}"

  local tmpdir
  tmpdir=$(mktemp -d)
  # rune.exe is a native Windows binary: MSYS virtual paths like /tmp/...
  # are not visible to it. Convert the scratch dir to a real Windows path.
  local win_tmpdir="$tmpdir"
  if command -v cygpath >/dev/null 2>&1; then
    win_tmpdir=$(cygpath -m "$tmpdir")
  fi

  # Discover eligible cases first (registration order preserved for output).
  local bases=()
  for ss_file in "$TEST_DIR"/*.ss; do
    [ -f "$ss_file" ] || continue
    local base
    base=$(basename "$ss_file" .ss)
    if [ -n "$filter" ] && [[ "$base" != *"$filter"* ]]; then continue; fi
    if [ -n "$skip_re" ] && [[ "$base" =~ $skip_re ]]; then continue; fi
    if [ -n "$include_re" ] && ! [[ "$base" =~ $include_re ]]; then continue; fi
    if [ ! -f "$EXPECTED_DIR/$base$suffix" ]; then
      skip "$base" "no golden file"
      continue
    fi
    bases+=("$base")
  done

  # Phase 1: single-process batch compile (manifest with absolute paths).
  local manifest="$win_tmpdir/manifest.tsv"
  : > "$manifest"
  local i
  for i in "${!bases[@]}"; do
    printf '%s\t%s\t%s\n' "$TEST_DIR/${bases[$i]}.ss" "$win_tmpdir/$i.out" "${dialect:-mysql}" >> "$manifest"
  done
  local batch_rc=0
  "$COMPILER" compile-batch "$manifest" > /dev/null 2>&1 || batch_rc=$?

  # Phase 2: diff all outputs against goldens in ONE awk process.
  # awk loads each golden, streams its compiled twin, and writes a
  # per-case status file — zero shell forks for the comparison itself.
  : > "$tmpdir/statuses.tsv"
  for i in "${!bases[@]}"; do
    printf '%d\t%s\t%s\t%s\n' "$i" "$EXPECTED_DIR/${bases[$i]}$suffix" "$win_tmpdir/$i.out" "$win_tmpdir/$i.status" >> "$tmpdir/pairs.tsv"
  done
  if [ -f "$tmpdir/pairs.tsv" ]; then
    awk -F'\t' '
      {
        idx = $1; expf = $2; outf = $3; stf = $4
        delete elines; n = 0
        while ((getline line < expf) > 0) {
          sub(/\r$/, "", line)
          if (line !~ /^-- Generated by rune / && line !~ /^# Generated by rune / && line !~ /"version": "[0-9]/)
            elines[++n] = line
        }
        close(expf)
        c = 0; ok = 1; empty_out = 1
        while ((getline line < outf) > 0) {
          sub(/\r$/, "", line)
          empty_out = 0
          if (line !~ /^-- Generated by rune / && line !~ /^# Generated by rune / && line !~ /"version": "[0-9]/) {
            c++
            if (c > n || line != elines[c]) { ok = 0 }
          }
        }
        close(outf)
        if (empty_out == 1) { ok = 0 }
        else if (c != n) { ok = 0 }
        if (ok) { printf "PASS\n" > stf; } else { printf "FAIL:output differs from golden %s\n", expf > stf; }
        close(stf)
      }
    ' "$tmpdir/pairs.tsv"
  fi

  # Report in original order. If the whole batch failed to launch, mark all.
  for i in "${!bases[@]}"; do
    local status
    status=$(cat "$tmpdir/$i.status" 2>/dev/null || { [ "$batch_rc" -ne 0 ] && echo "FAIL:batch compiler failed" || echo "FAIL:no status"; })
    case "$status" in
      PASS) pass "${bases[$i]}" ;;
      FAIL:*) fail "${bases[$i]}" "${status#FAIL:}" ;;
    esac
  done

  rm -rf "$tmpdir"
}

# Get diff output for error messages, ignoring version strings.
# Safe under pipefail — uses process substitution instead of pipe.
diff_versions() {
  local expected="$1" actual="$2"
  diff -u <(strip_version_auto "$expected") <(strip_version_auto "$actual") 2>&1 | head -20 || true
}
