#!/bin/bash
# ── Rune Test Library ──
# Shared functions for all test runners.
# Source this file: source "$(dirname "$0")/lib.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Detect binary name: .exe on Windows/MSYS, plain name on Linux/macOS
if [[ "$OSTYPE" == msys* || "$OSTYPE" == cygwin* || "$OSTYPE" == win32 ]]; then
  BIN_SUFFIX=".exe"
else
  BIN_SUFFIX=""
fi
COMPILER="$PROJECT_DIR/rune/zig-out/bin/rune${BIN_SUFFIX}"

# Ensure compiler exists
if [ ! -f "$COMPILER" ]; then
  echo "ERROR: Compiler not found at $COMPILER"
  echo "Run 'cd rune && zig build' first."
  exit 1
fi

PASS=0
FAIL=0
SKIP=0
ERRORS=""

pass() {
  printf "  \033[32m✅\033[0m %s\n" "$1"
  PASS=$((PASS + 1))
}

fail() {
  printf "  \033[31m❌\033[0m %s\n" "$1"
  if [ -n "${2:-}" ]; then
    printf "     \033[90m%s\033[0m\n" "$2"
  fi
  FAIL=$((FAIL + 1))
  ERRORS="$ERRORS $1"
}

skip() {
  printf "  \033[33m⏭\033[0m  %s  (%s)\n" "$1" "${2:-skipped}"
  SKIP=$((SKIP + 1))
}

header() {
  echo ""
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
  printf "\033[1m%s\033[0m\n" "$1"
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
  echo ""
}

summary() {
  local label="${1:-Tests}"
  local total=$((PASS + FAIL))
  echo ""
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
  if [ $FAIL -eq 0 ]; then
    printf "\033[32m%s: %d/%d passed\033[0m\n" "$label" "$PASS" "$total"
  else
    printf "\033[31m%s: %d/%d passed, %d failed\033[0m\n" "$label" "$PASS" "$total" "$FAIL"
  fi
  if [ $SKIP -gt 0 ]; then
    printf "\033[33m  (%d skipped)\033[0m\n" "$SKIP"
  fi
  if [ -n "$ERRORS" ]; then
    printf "\033[31mFailed:%s\033[0m\n" "$ERRORS"
  fi
  printf "\033[1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n"
}

# Strip the "Generated by rune X.Y.Z" version comment from SQL output.
# This makes golden tests resilient to version bumps.
strip_version() {
  grep -v '^-- Generated by rune ' || true
}

# Compare two files ignoring the "Generated by rune" version comment.
# Usage: compare_files <expected> <actual>
# Returns 0 if identical (ignoring version), 1 if different.
compare_files() {
  local expected="$1" actual="$2"
  diff <(strip_version < "$expected") <(strip_version < "$actual") > /dev/null 2>&1
}

# Get diff output for error messages, ignoring version comments.
# Safe under pipefail — uses process substitution instead of pipe.
diff_versions() {
  local expected="$1" actual="$2"
  diff -u <(strip_version < "$expected") <(strip_version < "$actual") 2>&1 | head -20 || true
}
