
CREATE TABLE "all_types" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "full" CLOB NOT NULL,
  "price" DECIMAL(16, 2) NOT NULL,
  "big_p" DECIMAL(20, 6) NOT NULL,
  "flag" BOOLEAN NOT NULL,
  "data" BLOB NOT NULL,
  "meta" CLOB NOT NULL,
  "created" TIMESTAMP NOT NULL,
  "born" DATE NOT NULL,
  "code" VARCHAR(64) NOT NULL,
  "ver" BIGINT NOT NULL,
  "amt" DECIMAL(10, 2) NOT NULL,
  "cnt" INTEGER NOT NULL
);
