-- Generated by rune 0.66.0

CREATE TABLE "all_types" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(255),
  "full" CLOB,
  "price" NUMBER(16, 2),
  "big_p" NUMBER(20, 6),
  "flag" NUMBER(1),
  "data" BLOB,
  "meta" CLOB,
  "created" TIMESTAMP,
  "born" DATE,
  "code" VARCHAR2(64),
  "ver" NUMBER(19),
  "amt" NUMBER(10, 2),
  "cnt" NUMBER(10)
);
