-- Generated by rune 0.69.0

CREATE TABLE "all_types" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(255),
  "full" CLOB,
  "price" DECIMAL(16, 2),
  "big_p" DECIMAL(20, 6),
  "flag" BOOLEAN,
  "data" BLOB,
  "meta" CLOB,
  "created" TIMESTAMP,
  "born" DATE,
  "code" VARCHAR(64),
  "ver" BIGINT,
  "amt" DECIMAL(10, 2),
  "cnt" INTEGER
);
