
CREATE TABLE [all_types] (
  [id] INT NOT NULL PRIMARY KEY,
  [name] NVARCHAR(255) NOT NULL,
  [full] NVARCHAR(MAX) NOT NULL,
  [price] NUMERIC(16, 2) NOT NULL,
  [big_p] NUMERIC(20, 6) NOT NULL,
  [flag] BIT NOT NULL,
  [data] VARBINARY(MAX) NOT NULL,
  [meta] NVARCHAR(MAX) NOT NULL,
  [created] DATETIME2 NOT NULL,
  [born] DATE NOT NULL,
  [code] NVARCHAR(64) NOT NULL,
  [ver] BIGINT NOT NULL,
  [amt] NUMERIC(10, 2) NOT NULL,
  [cnt] INT NOT NULL
);
