
CREATE TABLE "modifiers" (
  "col1" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "col2" INTEGER NOT NULL,
  "col3" INTEGER NOT NULL PRIMARY KEY,
  "col4" INTEGER NOT NULL,
  "col5" INTEGER NOT NULL DEFAULT 0,
  "col6" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "col7" INTEGER NOT NULL PRIMARY KEY,
  "col8" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "col9" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
