
CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `modifiers` (
  `col1` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `col2` int NOT NULL AUTO_INCREMENT,
  `col3` int NOT NULL PRIMARY KEY,
  `col4` int NOT NULL,
  `col5` int NOT NULL DEFAULT 0,
  `col6` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `col7` int NOT NULL PRIMARY KEY,
  `col8` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `col9` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
