
CREATE TABLE [modifiers] (
  [col1] INT NOT NULL PRIMARY KEY,
  [col2] INT NOT NULL,
  [col3] INT NOT NULL PRIMARY KEY,
  [col4] INT NOT NULL,
  [col5] INT NOT NULL DEFAULT 0,
  [col6] INT NOT NULL PRIMARY KEY,
  [col7] INT NOT NULL PRIMARY KEY,
  [col8] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  [col9] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);
