
CREATE TABLE "defaults" (
  "col1" INTEGER NOT NULL DEFAULT 0,
  "col2" VARCHAR(255) NOT NULL DEFAULT 'hello',
  "col3" DECIMAL(16, 2) NOT NULL DEFAULT 0,
  "col4" VARCHAR(255) NOT NULL DEFAULT 0,
  "col5" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
