
CREATE TABLE "defaults" (
  "col1" NUMBER(10) NOT NULL DEFAULT 0,
  "col2" VARCHAR2(255) NOT NULL DEFAULT 'hello',
  "col3" NUMBER(16, 2) NOT NULL DEFAULT 0,
  "col4" VARCHAR2(255) NOT NULL DEFAULT 0,
  "col5" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
