
CREATE TABLE [defaults] (
  [col1] INT DEFAULT 0,
  [col2] NVARCHAR(255) DEFAULT 'hello',
  [col3] NUMERIC(16, 2) DEFAULT 0,
  [col4] NVARCHAR(255) DEFAULT 0,
  [col5] DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
