
CREATE TABLE [defaults] (
  [col1] INT NOT NULL DEFAULT 0,
  [col2] NVARCHAR(255) NOT NULL DEFAULT 'hello',
  [col3] NUMERIC(16, 2) NOT NULL DEFAULT 0,
  [col4] NVARCHAR(255) NOT NULL DEFAULT 0,
  [col5] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);
