-- Generated by rune 0.75.0

CREATE TABLE "suffixes" (
  "user_id" NUMBER(10),
  "order_id" NUMBER(10),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "paid_on" DATE,
  "deleted_on" DATE,
  "name" VARCHAR2(255),
  "content" VARCHAR2(255)
);
