-- Generated by rune 0.69.0

CREATE TABLE "suffixes" (
  "user_id" INTEGER,
  "order_id" INTEGER,
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "paid_on" DATE,
  "deleted_on" DATE,
  "name" VARCHAR(255),
  "content" VARCHAR(255)
);
