-- Generated by rune 0.320.0 [mssql]

-- This is a SQL comment (passed through)
CREATE TABLE [comments] (
  [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL /* 用户名 */,
  [email] NVARCHAR(128) NOT NULL /* 邮箱地址 */,
  [bio] NVARCHAR(MAX) NOT NULL /* 个人简介 */
);
