-- Generated by rune 0.75.0

-- This is a SQL comment (passed through)
CREATE TABLE "comments" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL /* 用户名 */,
  "email" VARCHAR2(128) NOT NULL /* 邮箱地址 */,
  "bio" CLOB /* 个人简介 */
);
COMMENT ON COLUMN "comments"."name" IS '用户名';
COMMENT ON COLUMN "comments"."email" IS '邮箱地址';
COMMENT ON COLUMN "comments"."bio" IS '个人简介';
