
CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `my_table` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='这是一个测试表';
