
CREATE TABLE [user] (
  [id] INT NOT NULL PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL,
  [email] NVARCHAR(128) NOT NULL,
  [version] BIGINT NOT NULL,
  [create_at] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);
