-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "version" NUMBER(19),
  "create_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
