-- Generated by rune 0.55.0

CREATE TABLE [user] (
  [id] INT PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL,
  [email] NVARCHAR(128) NOT NULL,
  [version] BIGINT,
  [create_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
