
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "version" BIGINT NOT NULL,
  "create_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
