
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "amount" DECIMAL(16, 2) NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id") ON UPDATE CASCADE
);
