
CREATE TABLE "unsigned_test" (
  "plain_n" INTEGER NOT NULL,
  "plain_N" BIGINT NOT NULL,
  "plus_n" INTEGER NOT NULL,
  "plus_N" BIGINT NOT NULL,
  "plus_n_pk" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "plus_N_nn" BIGINT NOT NULL
);
