-- Generated by rune 0.66.0

CREATE TABLE "unsigned_test" (
  "plain_n" NUMBER(10),
  "plain_N" NUMBER(19),
  "plus_n" NUMBER(10),
  "plus_N" NUMBER(19),
  "plus_n_pk" NUMBER(10) PRIMARY KEY,
  "plus_N_nn" NUMBER(19) NOT NULL
);
