-- Generated by rune 0.69.0

CREATE TABLE "unsigned_test" (
  "plain_n" INTEGER,
  "plain_N" BIGINT,
  "plus_n" INTEGER,
  "plus_N" BIGINT,
  "plus_n_pk" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "plus_N_nn" BIGINT NOT NULL
);
