-- Generated by rune 0.55.0

CREATE TABLE [user] (
  [name] NVARCHAR(32) NOT NULL,
  [email] NVARCHAR(128) NOT NULL,
  [id] INT PRIMARY KEY,
  [create_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  [update_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  [version] BIGINT,
  [status] INT DEFAULT 0
);
