
CREATE TABLE [user] (
  [name] NVARCHAR(32) NOT NULL,
  [email] NVARCHAR(128) NOT NULL,
  [id] INT NOT NULL PRIMARY KEY,
  [create_at] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  [update_at] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  [version] BIGINT NOT NULL,
  [status] INT NOT NULL DEFAULT 0
);
