
CREATE TABLE "user" (
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "create_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "version" BIGINT NOT NULL,
  "status" INTEGER NOT NULL DEFAULT 0,
  "deleted_at" TIMESTAMP NOT NULL,
  "deleted_by" INTEGER NOT NULL
);
