-- Generated by rune 0.75.0

CREATE TABLE "item" (
  "name" VARCHAR2(64) NOT NULL,
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" NUMBER(10) DEFAULT 0,
  "version" NUMBER(19)
);
