-- Generated by rune 0.38.0

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `item` (
  `name` varchar(64) NOT NULL,
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `status` int DEFAULT 0,
  `version` bigint
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
