-- Generated by rune 0.51.0

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "parent" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE "child" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "parent_id" integer,
  FOREIGN KEY ("parent_id") REFERENCES "parent"("id")
);
