-- Generated by rune 0.66.0

CREATE TABLE "parent" (
  "id" NUMBER(10) PRIMARY KEY
);

CREATE TABLE "child" (
  "id" NUMBER(10) PRIMARY KEY,
  "parent_id" NUMBER(10),
  FOREIGN KEY ("parent_id") REFERENCES "parent"("id")
);
