
CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "parent" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE "child" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "parent_id" integer NOT NULL,
  FOREIGN KEY ("parent_id") REFERENCES "parent"("id")
);
