
CREATE TABLE "indexed" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "content" CLOB NOT NULL,
  UNIQUE "uk_email" ("email"),
  INDEX "idx_name" ("name"),
  INDEX "ft_content" ("content")
);
