-- Generated by rune 0.75.0

CREATE TABLE "indexed" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32),
  "email" VARCHAR2(128),
  "content" CLOB,
  UNIQUE "uk_email" ("email"),
  INDEX "idx_name" ("name"),
  INDEX "ft_content" ("content")
);
