-- Generated by rune 0.320.0 [mssql]

CREATE TABLE [indexed] (
  [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL,
  [email] NVARCHAR(128) NOT NULL,
  [content] NVARCHAR(MAX) NOT NULL,
  UNIQUE [uk_email] ([email]),
  INDEX [idx_name] ([name]),
  FULLTEXT INDEX [ft_content] ([content])
);
