-- Generated by rune 0.69.0

CREATE TABLE "indexed" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32),
  "email" VARCHAR(128),
  "content" CLOB,
  UNIQUE "uk_email" ("email"),
  INDEX "idx_name" ("name"),
  INDEX "ft_content" ("content")
);
