-- Generated by rune 0.55.0

CREATE TABLE [indexed] (
  [id] INT PRIMARY KEY,
  [name] NVARCHAR(32),
  [email] NVARCHAR(128),
  [content] NVARCHAR(MAX),
  UNIQUE [uk_email] ([email]),
  INDEX [idx_name] ([name]),
  FULLTEXT INDEX [ft_content] ([content])
);
