-- Generated by rune 0.66.0

CREATE TABLE "multi" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32),
  "email" VARCHAR2(128),
  "status" NUMBER(10),
  INDEX "idx_name_email" ("name", "email"),
  UNIQUE "uk_email_status" ("email", "status")
);
