
CREATE TABLE "multi" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "status" NUMBER(10) NOT NULL,
  INDEX "idx_name_email" ("name", "email"),
  UNIQUE "uk_email_status" ("email", "status")
);
