-- Generated by rune 0.69.0

CREATE TABLE "constrained" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "age" INTEGER CHECK (age BETWEEN 0 AND 150),
  "score" DECIMAL(16, 2) CHECK (score BETWEEN 0 AND 100),
  "amount" DECIMAL(16, 2) CHECK (amount > 0),
  "qty" INTEGER CHECK (qty >= 1),
  "type" VARCHAR(16) CHECK (type IN ('a', 'b', 'c')),
  "range2" INTEGER CHECK (range2 >= 0 AND range2 <= 100)
);
