-- Generated by rune 0.66.0

CREATE TABLE "constrained" (
  "id" NUMBER(10) PRIMARY KEY,
  "age" NUMBER(10) CHECK (age BETWEEN 0 AND 150),
  "score" NUMBER(16, 2) CHECK (score BETWEEN 0 AND 100),
  "amount" NUMBER(16, 2) CHECK (amount > 0),
  "qty" NUMBER(10) CHECK (qty >= 1),
  "type" VARCHAR2(16) CHECK (type IN ('a', 'b', 'c')),
  "range2" NUMBER(10) CHECK (range2 >= 0 AND range2 <= 100)
);
