-- Generated by rune 0.320.0 [mssql]

CREATE TABLE [constrained] (
  [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [age] INT NOT NULL CHECK (age BETWEEN 0 AND 150),
  [score] NUMERIC(16, 2) NOT NULL CHECK (score BETWEEN 0 AND 100),
  [amount] NUMERIC(16, 2) NOT NULL CHECK (amount > 0),
  [qty] INT NOT NULL CHECK (qty >= 1),
  [type] NVARCHAR(16) NOT NULL CHECK (type IN ('a', 'b', 'c')),
  [range2] INT NOT NULL CHECK (range2 >= 0 AND range2 <= 100)
);
