
CREATE TABLE "constrained" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "age" NUMBER(10) NOT NULL CHECK (age BETWEEN 0 AND 150),
  "score" NUMBER(16, 2) NOT NULL CHECK (score BETWEEN 0 AND 100),
  "amount" NUMBER(16, 2) NOT NULL CHECK (amount > 0),
  "qty" NUMBER(10) NOT NULL CHECK (qty >= 1),
  "type" VARCHAR2(16) NOT NULL CHECK (type IN ('a', 'b', 'c')),
  "range2" NUMBER(10) NOT NULL CHECK (range2 >= 0 AND range2 <= 100)
);
