-- Generated by rune 0.66.0

-- Users table
CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL
);

CREATE TABLE "order" (
  "id" NUMBER(10) PRIMARY KEY,
  "user_id" NUMBER(10),
  "amount" NUMBER(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
