-- Generated by rune 0.32.0

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `simple` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
