-- Generated by rune 0.31.0

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `mytable` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
