-- Generated by rune 0.329.0 [pg]

CREATE DATABASE "shop" ENCODING 'UTF8';

CREATE TABLE "users" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(128) NOT NULL,
  UNIQUE ("email")
);

CREATE TABLE "orders" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "amount" numeric(16, 2) NOT NULL CHECK (amount > 0),
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
);
