-- Generated by rune 0.48.0

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `spaced` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
