
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "version" BIGINT NOT NULL,
  "status" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "product" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "price" DECIMAL(16, 2) NOT NULL,
  "version" BIGINT NOT NULL,
  "status" INTEGER NOT NULL DEFAULT 0
);
