-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "version" NUMBER(19),
  "status" NUMBER(10) DEFAULT 0
);

CREATE TABLE "product" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(128) NOT NULL,
  "price" NUMBER(16, 2),
  "version" NUMBER(19),
  "status" NUMBER(10) DEFAULT 0
);
