-- Generated by rune 0.66.0

CREATE TABLE "compound_check" (
  "id" NUMBER(10) PRIMARY KEY,
  "balance" NUMBER(16, 2) CHECK (balance >= 0 AND balance <= 99999),
  "score" NUMBER(10) CHECK (score > 0 AND score <= 100)
);
