-- Generated by rune 0.69.0

CREATE TABLE "compound_check" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "balance" DECIMAL(16, 2) CHECK (balance >= 0 AND balance <= 99999),
  "score" INTEGER CHECK (score > 0 AND score <= 100)
);
