
CREATE TABLE "compound_check" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "balance" NUMBER(16, 2) NOT NULL CHECK (balance >= 0 AND balance <= 99999),
  "score" NUMBER(10) NOT NULL CHECK (score > 0 AND score <= 100)
);
