-- Generated by rune 0.31.0

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "bare_fields" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "order_id" integer,
  "name" varchar(255)
);
