-- Generated by rune 0.49.0

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `composite_pk` (
  `user_id` int PRIMARY KEY,
  `role_id` int PRIMARY KEY,
  `granted` datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
