-- Generated by rune 0.75.0

CREATE TABLE "category" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(64) NOT NULL
);

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL
);

CREATE TABLE "order" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" NUMBER(10),
  "category_id" NUMBER(10),
  "amount" NUMBER(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id"),
  FOREIGN KEY ("category_id") REFERENCES "category"("id")
);
