-- Generated by rune 0.69.0

CREATE TABLE "category" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(64) NOT NULL
);

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER,
  "category_id" INTEGER,
  "amount" DECIMAL(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id"),
  FOREIGN KEY ("category_id") REFERENCES "category"("id")
);
