-- Generated by rune 0.55.0

CREATE TABLE [category] (
  [id] INT PRIMARY KEY,
  [name] NVARCHAR(64) NOT NULL
);

CREATE TABLE [user] (
  [id] INT PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL
);

CREATE TABLE [order] (
  [id] INT PRIMARY KEY,
  [user_id] INT,
  [category_id] INT,
  [amount] NUMERIC(16, 2),
  FOREIGN KEY ([user_id]) REFERENCES [user]([id]),
  FOREIGN KEY ([category_id]) REFERENCES [category]([id])
);
