-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "version" NUMBER(19),
  "status" NUMBER(10) DEFAULT 0,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL
);
