
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "version" BIGINT NOT NULL,
  "status" INTEGER NOT NULL DEFAULT 0,
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL
);
