-- Generated by rune 0.57.0

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `user` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `version` bigint,
  `status` int DEFAULT 0,
  `name` varchar(32) NOT NULL,
  `email` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
