-- Generated by rune 0.55.0

CREATE TABLE [user] (
  [id] INT PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL /* 用户登录名 */,
  [email] NVARCHAR(128) NOT NULL /* 唯一邮箱 */,
  [password] NVARCHAR(256) NOT NULL /* bcrypt hash */,
  [avatar] NVARCHAR(MAX) /* 头像 URL */,
  [is_admin] BIT DEFAULT 0 /* 管理员标记 */,
  [balance] NUMERIC(16, 2) DEFAULT 0 /* 账户余额（分） */,
  [settings] NVARCHAR(MAX) /* JSON 用户偏好 */,
  [version] BIGINT,
  [status] INT DEFAULT 0,
  [delete_at] DATETIME2,
  [create_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  [update_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  UNIQUE [uk_email] ([email]),
  INDEX [idx_name] ([name])
);

CREATE TABLE [product] (
  [id] INT PRIMARY KEY,
  [name] NVARCHAR(128) NOT NULL /* 商品名称 */,
  [description] NVARCHAR(MAX) /* 商品详情 */,
  [price] NUMERIC(16, 2) NOT NULL /* 单价（分） */,
  [stock] INT DEFAULT 0 /* 库存数量 */,
  [category_id] INT /* 分类 ID */,
  [version] BIGINT,
  [status] INT DEFAULT 0,
  [delete_at] DATETIME2,
  [create_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  [update_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  INDEX [idx_category_id] ([category_id]),
  INDEX [idx_price] ([price])
);

CREATE TABLE [order] (
  [id] INT PRIMARY KEY,
  [order_no] NVARCHAR(64) NOT NULL /* 唯一订单号 */,
  [user_id] INT /* 下单用户 */,
  [amount] NUMERIC(16, 2) NOT NULL /* 订单总额（分） */,
  [discount] NUMERIC(20, 6) DEFAULT 0 /* 折扣金额（分） */,
  [note] NVARCHAR(512) /* 买家留言 */,
  [paid_on] DATE /* 支付日期 */,
  [version] BIGINT,
  [status] INT DEFAULT 0,
  [delete_at] DATETIME2,
  [create_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  [update_at] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  UNIQUE [uk_order_no] ([order_no]),
  INDEX [idx_user_id] ([user_id]),
  INDEX [idx_paid_on] ([paid_on]),
  FOREIGN KEY ([user_id]) REFERENCES [user]([id])
);
