
CREATE TABLE "user" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL /* 用户登录名 */,
  "email" VARCHAR2(128) NOT NULL /* 唯一邮箱 */,
  "password" VARCHAR2(256) NOT NULL /* bcrypt hash */,
  "avatar" CLOB NOT NULL /* 头像 URL */,
  "is_admin" NUMBER(1) NOT NULL DEFAULT 0 /* 管理员标记 */,
  "balance" NUMBER(16, 2) NOT NULL DEFAULT 0 /* 账户余额（分） */,
  "settings" CLOB NOT NULL /* JSON 用户偏好 */,
  "version" NUMBER(19) NOT NULL,
  "status" NUMBER(10) NOT NULL DEFAULT 0,
  "delete_at" TIMESTAMP NOT NULL,
  "create_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE "uk_email" ("email"),
  INDEX "idx_name" ("name")
);
COMMENT ON TABLE "user" IS '用户表';
COMMENT ON COLUMN "user"."name" IS '用户登录名';
COMMENT ON COLUMN "user"."email" IS '唯一邮箱';
COMMENT ON COLUMN "user"."password" IS 'bcrypt hash';
COMMENT ON COLUMN "user"."avatar" IS '头像 URL';
COMMENT ON COLUMN "user"."is_admin" IS '管理员标记';
COMMENT ON COLUMN "user"."balance" IS '账户余额（分）';
COMMENT ON COLUMN "user"."settings" IS 'JSON 用户偏好';

CREATE TABLE "product" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(128) NOT NULL /* 商品名称 */,
  "description" CLOB NOT NULL /* 商品详情 */,
  "price" NUMBER(16, 2) NOT NULL /* 单价（分） */,
  "stock" NUMBER(10) NOT NULL DEFAULT 0 /* 库存数量 */,
  "category_id" NUMBER(10) NOT NULL /* 分类 ID */,
  "version" NUMBER(19) NOT NULL,
  "status" NUMBER(10) NOT NULL DEFAULT 0,
  "delete_at" TIMESTAMP NOT NULL,
  "create_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX "idx_category_id" ("category_id"),
  INDEX "idx_price" ("price")
);
COMMENT ON TABLE "product" IS '商品表';
COMMENT ON COLUMN "product"."name" IS '商品名称';
COMMENT ON COLUMN "product"."description" IS '商品详情';
COMMENT ON COLUMN "product"."price" IS '单价（分）';
COMMENT ON COLUMN "product"."stock" IS '库存数量';
COMMENT ON COLUMN "product"."category_id" IS '分类 ID';

CREATE TABLE "order" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_no" VARCHAR2(64) NOT NULL /* 唯一订单号 */,
  "user_id" NUMBER(10) NOT NULL /* 下单用户 */,
  "amount" NUMBER(16, 2) NOT NULL /* 订单总额（分） */,
  "discount" NUMBER(20, 6) NOT NULL DEFAULT 0 /* 折扣金额（分） */,
  "note" VARCHAR2(512) NOT NULL /* 买家留言 */,
  "paid_on" DATE NOT NULL /* 支付日期 */,
  "version" NUMBER(19) NOT NULL,
  "status" NUMBER(10) NOT NULL DEFAULT 0,
  "delete_at" TIMESTAMP NOT NULL,
  "create_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE "uk_order_no" ("order_no"),
  INDEX "idx_user_id" ("user_id"),
  INDEX "idx_paid_on" ("paid_on"),
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
COMMENT ON TABLE "order" IS '订单表';
COMMENT ON COLUMN "order"."order_no" IS '唯一订单号';
COMMENT ON COLUMN "order"."user_id" IS '下单用户';
COMMENT ON COLUMN "order"."amount" IS '订单总额（分）';
COMMENT ON COLUMN "order"."discount" IS '折扣金额（分）';
COMMENT ON COLUMN "order"."note" IS '买家留言';
COMMENT ON COLUMN "order"."paid_on" IS '支付日期';
