
CREATE TABLE "defaults_many" (
  "col_int" INTEGER NOT NULL DEFAULT 42,
  "col_str" VARCHAR(255) NOT NULL DEFAULT 'hello',
  "col_zero" INTEGER NOT NULL DEFAULT 0,
  "col_one" INTEGER NOT NULL DEFAULT 1,
  "col_empty" VARCHAR(255) NOT NULL DEFAULT 0,
  "col_big" BIGINT NOT NULL DEFAULT 999999999,
  "col_m" DECIMAL(16, 2) NOT NULL DEFAULT 0
);
