-- Generated by rune 0.69.0

CREATE TABLE "defaults_many" (
  "col_int" INTEGER DEFAULT 42,
  "col_str" VARCHAR(255) DEFAULT 'hello',
  "col_zero" INTEGER DEFAULT 0,
  "col_one" INTEGER DEFAULT 1,
  "col_empty" VARCHAR(255) DEFAULT 0,
  "col_big" BIGINT DEFAULT 999999999,
  "col_m" DECIMAL(16, 2) DEFAULT 0
);
