-- Generated by rune 0.75.0

CREATE TABLE "defaults_many" (
  "col_int" NUMBER(10) DEFAULT 42,
  "col_str" VARCHAR2(255) DEFAULT 'hello',
  "col_zero" NUMBER(10) DEFAULT 0,
  "col_one" NUMBER(10) DEFAULT 1,
  "col_empty" VARCHAR2(255) DEFAULT 0,
  "col_big" NUMBER(19) DEFAULT 999999999,
  "col_m" NUMBER(16, 2) DEFAULT 0
);
