
CREATE TABLE "defaults_many" (
  "col_int" NUMBER(10) NOT NULL DEFAULT 42,
  "col_str" VARCHAR2(255) NOT NULL DEFAULT 'hello',
  "col_zero" NUMBER(10) NOT NULL DEFAULT 0,
  "col_one" NUMBER(10) NOT NULL DEFAULT 1,
  "col_empty" VARCHAR2(255) NOT NULL DEFAULT 0,
  "col_big" NUMBER(19) NOT NULL DEFAULT 999999999,
  "col_m" NUMBER(16, 2) NOT NULL DEFAULT 0
);
