
CREATE TABLE "standalone_mod" (
  "col1" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "col2" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "col3" VARCHAR(255) NOT NULL,
  "col4" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
