-- Generated by rune 0.51.0

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "phone" varchar(16),
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "email" varchar(128) NOT NULL,
  "name" varchar(64) NOT NULL,
  "version" bigint
);
