-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "phone" VARCHAR(16),
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "email" VARCHAR(128) NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "version" BIGINT
);
