-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "phone" VARCHAR2(16),
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR2(128) NOT NULL,
  "name" VARCHAR2(64) NOT NULL,
  "version" NUMBER(19)
);
