
CREATE TABLE "user" (
  "phone" VARCHAR(16) NOT NULL,
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "email" VARCHAR(128) NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "version" BIGINT NOT NULL
);
