
CREATE TABLE "status_check" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" VARCHAR2(16) NOT NULL CHECK (status IN ('active', 'inactive', 'pending')),
  "priority" NUMBER(10) NOT NULL CHECK (priority IN (1, 2, 3, 4, 5))
);
