-- Generated by rune 0.69.0

CREATE TABLE "status_check" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "status" VARCHAR(16) CHECK (status IN ('active', 'inactive', 'pending')),
  "priority" INTEGER CHECK (priority IN (1, 2, 3, 4, 5))
);
