-- Generated by rune 0.66.0

CREATE TABLE "status_check" (
  "id" NUMBER(10) PRIMARY KEY,
  "status" VARCHAR2(16) CHECK (status IN ('active', 'inactive', 'pending')),
  "priority" NUMBER(10) CHECK (priority IN (1, 2, 3, 4, 5))
);
