-- Generated by rune 0.55.0

CREATE TABLE [user] (
  [id] INT PRIMARY KEY,
  [gender] NVARCHAR(255) NOT NULL CHECK ([gender] IN ('M', 'F', 'X')),
  [status] NVARCHAR(255) DEFAULT 'pending' CHECK ([status] IN ('pending', 'active', 'closed')),
  [role] NVARCHAR(255) CHECK ([role] IN ('admin', 'user', 'guest'))
);
