-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gender" VARCHAR2(255) NOT NULL CHECK ("gender" IN ('M', 'F', 'X')),
  "status" VARCHAR2(255) DEFAULT 'pending' CHECK ("status" IN ('pending', 'active', 'closed')),
  "role" VARCHAR2(255) CHECK ("role" IN ('admin', 'user', 'guest'))
);
