-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "gender" VARCHAR(255) NOT NULL CHECK ("gender" IN ('M', 'F', 'X')),
  "status" VARCHAR(255) DEFAULT 'pending' CHECK ("status" IN ('pending', 'active', 'closed')),
  "role" VARCHAR(255) CHECK ("role" IN ('admin', 'user', 'guest'))
);
