
CREATE TABLE "user" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gender" VARCHAR2(255) NOT NULL CHECK ("gender" IN ('M', 'F', 'X')),
  "status" VARCHAR2(255) NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'active', 'closed')),
  "role" VARCHAR2(255) NOT NULL CHECK ("role" IN ('admin', 'user', 'guest'))
);
