-- Generated by rune 0.34.0

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "order_item" (
  "order_id" integer,
  "product_id" integer,
  "quantity" integer,
  PRIMARY KEY ("order_id", "product_id")
);
