-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "email" VARCHAR2(128) NOT NULL,
  "name" VARCHAR2(32),
  "code" VARCHAR2(16),
  UNIQUE INDEX "uk_email" ("email"),
  UNIQUE INDEX "uk_code" ("code")
);
