-- Generated by rune 0.320.0 [mssql]

CREATE TABLE [user] (
  [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [email] NVARCHAR(128) NOT NULL,
  [name] NVARCHAR(32) NOT NULL,
  [code] NVARCHAR(16) NOT NULL,
  UNIQUE INDEX [uk_email] ([email]),
  UNIQUE INDEX [uk_code] ([code])
);
