
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "email" VARCHAR(128) NOT NULL,
  "name" VARCHAR(32) NOT NULL,
  "code" VARCHAR(16) NOT NULL,
  UNIQUE INDEX "uk_email" ("email"),
  UNIQUE INDEX "uk_code" ("code")
);
