-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "email" VARCHAR(128) NOT NULL,
  "name" VARCHAR(32),
  "code" VARCHAR(16),
  UNIQUE INDEX "uk_email" ("email"),
  UNIQUE INDEX "uk_code" ("code")
);
