-- Generated by rune 0.55.0

CREATE TABLE [user] (
  [id] INT PRIMARY KEY,
  [email] NVARCHAR(128) NOT NULL,
  [name] NVARCHAR(32),
  [code] NVARCHAR(16),
  UNIQUE INDEX [uk_email] ([email]),
  UNIQUE INDEX [uk_code] ([code])
);
