-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "version" BIGINT,
  "deleted_at" TIMESTAMP,
  "deleted_by" INTEGER,
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "phone" VARCHAR(16)
);
