
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "version" BIGINT NOT NULL,
  "deleted_at" TIMESTAMP NOT NULL,
  "deleted_by" INTEGER NOT NULL,
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "phone" VARCHAR(16) NOT NULL
);
