-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "version" NUMBER(19),
  "deleted_at" TIMESTAMP,
  "deleted_by" NUMBER(10),
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "phone" VARCHAR2(16)
);
