-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY
);

CREATE TABLE "order" (
  "id" NUMBER(10) PRIMARY KEY,
  "order_no" VARCHAR2(64) NOT NULL,
  "amount" NUMBER(16, 2) NOT NULL,
  FOREIGN KEY ("id") REFERENCES "user"("id")
);
