-- Generated by rune 0.69.0

CREATE TABLE "auth" (
  "email" VARCHAR(128) NOT NULL
);

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "email" VARCHAR(128) NOT NULL,
  "name" VARCHAR(32) NOT NULL,
  UNIQUE INDEX "uk_email" ("email"),
  FOREIGN KEY ("email") REFERENCES "auth"("email")
);
