-- Generated by rune 0.66.0

CREATE TABLE "auth" (
  "email" VARCHAR2(128) NOT NULL
);

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "email" VARCHAR2(128) NOT NULL,
  "name" VARCHAR2(32) NOT NULL,
  UNIQUE INDEX "uk_email" ("email"),
  FOREIGN KEY ("email") REFERENCES "auth"("email")
);
