-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32),
  "email" VARCHAR2(128),
  "status" NUMBER(10) DEFAULT 0,
  "create_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX "idx_name_email" ("name", "email"),
  UNIQUE "uk_email_status" ("email", "status")
);
