-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32),
  "email" VARCHAR(128),
  "status" INTEGER DEFAULT 0,
  "create_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX "idx_name_email" ("name", "email"),
  UNIQUE "uk_email_status" ("email", "status")
);
