-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32)
);

CREATE TABLE "order" (
  "id" NUMBER(10) PRIMARY KEY,
  "order_no" VARCHAR2(64) NOT NULL,
  "user_id" NUMBER(10) NOT NULL,
  "amount" NUMBER(16, 2) NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
