-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL
);

CREATE TABLE "order" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_no" VARCHAR2(64) NOT NULL,
  "user_id" NUMBER(10),
  "amount" NUMBER(16, 2) NOT NULL,
  INDEX "idx_user_id" ("user_id"),
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
