-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL,
  "email" VARCHAR(128) NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "order_no" VARCHAR(64) NOT NULL,
  "user_id" INTEGER,
  "amount" DECIMAL(16, 2) NOT NULL,
  INDEX "idx_user_id" ("user_id"),
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
