-- Generated by rune 0.320.0 [mssql]

CREATE TABLE [user] (
  [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL,
  [email] NVARCHAR(128) NOT NULL,
  [phone] NVARCHAR(16) NOT NULL,
  INDEX [idx_name] ([name]),
  UNIQUE INDEX [uk_email] ([email])
);
CREATE INDEX [idx_name_user] ON [user] ([name]);
