
CREATE TABLE "user" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "phone" VARCHAR2(16) NOT NULL,
  INDEX "idx_name" ("name"),
  UNIQUE INDEX "uk_email" ("email")
);
CREATE INDEX "idx_user_name" ON "user" ("name");
