-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32),
  "email" VARCHAR2(128) NOT NULL,
  "phone" VARCHAR2(16),
  INDEX "idx_name" ("name"),
  UNIQUE INDEX "uk_email" ("email")
);
CREATE INDEX "idx_user_name" ON "user" ("name");
