-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32),
  "email" VARCHAR(128) NOT NULL,
  "phone" VARCHAR(16),
  INDEX "idx_name" ("name"),
  UNIQUE INDEX "uk_email" ("email")
);
CREATE INDEX "idx_user_name" ON "user" ("name");
