
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL DEFAULT 0,
  "email" VARCHAR(128) NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT 1,
  "status" INTEGER NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2)),
  "balance" DECIMAL(16, 2) NOT NULL DEFAULT 0.00,
  "role" VARCHAR(32) NOT NULL DEFAULT 'admin'
);
