-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32)
);

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "order_no" VARCHAR(64),
  "amount" DECIMAL(16, 2) NOT NULL,
  FOREIGN KEY ("order_no") REFERENCES "order"("order_no")
);
