
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "order_no" VARCHAR(64) NOT NULL,
  "amount" DECIMAL(16, 2) NOT NULL,
  FOREIGN KEY ("order_no") REFERENCES "order"("order_no")
);
