
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL
);

CREATE TABLE "t1" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t2" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t3" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t4" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t5" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "t6" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "user"("id")
);
