-- Generated by rune 0.75.0

CREATE TABLE "users" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" VARCHAR2(255) CHECK ("role" IN ('admin', 'user', 'guest')),
  "status" VARCHAR2(255) CHECK ("status" IN ('A', 'B', 'C'))
);
