
CREATE TABLE "users" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" VARCHAR2(255) NOT NULL CHECK ("role" IN ('admin', 'user', 'guest')),
  "status" VARCHAR2(255) NOT NULL CHECK ("status" IN ('A', 'B', 'C'))
);
