
CREATE TABLE "constrained" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "age" NUMBER(10) NOT NULL CHECK (age BETWEEN 0 AND 150),
  "amount" NUMBER(16, 2) NOT NULL CHECK (amount > 0),
  "ratio" NUMBER(20, 6) NOT NULL CHECK (ratio >= 0 AND ratio <= 100),
  "type" VARCHAR2(16) NOT NULL CHECK (type IN ('a', 'b', 'c'))
);
