-- Generated by rune 0.69.0

CREATE TABLE "constrained" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "age" INTEGER CHECK (age BETWEEN 0 AND 150),
  "amount" DECIMAL(16, 2) CHECK (amount > 0),
  "ratio" DECIMAL(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  "type" VARCHAR(16) CHECK (type IN ('a', 'b', 'c'))
);
