-- Generated by rune 0.66.0

CREATE TABLE "constrained" (
  "id" NUMBER(10) PRIMARY KEY,
  "age" NUMBER(10) CHECK (age BETWEEN 0 AND 150),
  "amount" NUMBER(16, 2) CHECK (amount > 0),
  "ratio" NUMBER(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  "type" VARCHAR2(16) CHECK (type IN ('a', 'b', 'c'))
);
