-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "age_upper" NUMBER(10) DEFAULT 0 CHECK (age_upper >= 0 AND age_upper < 150),
  "age_lower" NUMBER(10) DEFAULT 0 CHECK (age_lower > 0 AND age_lower <= 150),
  "age_both" NUMBER(10) DEFAULT 0 CHECK (age_both > 0 AND age_both < 150)
);
