-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "age_upper" INTEGER DEFAULT 0 CHECK (age_upper >= 0 AND age_upper < 150),
  "age_lower" INTEGER DEFAULT 0 CHECK (age_lower > 0 AND age_lower <= 150),
  "age_both" INTEGER DEFAULT 0 CHECK (age_both > 0 AND age_both < 150)
);
