-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "status" INTEGER DEFAULT 0 CHECK (status IN (0, 1, 2)),
  "type" VARCHAR(16) CHECK (type IN ('a', 'b', 'c')),
  "level" INTEGER CHECK (level IN (1, 2, 3, 4, 5))
);
