
CREATE TABLE "user" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" NUMBER(10) NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2)),
  "type" VARCHAR2(16) NOT NULL CHECK (type IN ('a', 'b', 'c')),
  "level" NUMBER(10) NOT NULL CHECK (level IN (1, 2, 3, 4, 5))
);
