-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "status" NUMBER(10) DEFAULT 0 CHECK (status IN (0, 1, 2)),
  "type" VARCHAR2(16) CHECK (type IN ('a', 'b', 'c')),
  "level" NUMBER(10) CHECK (level IN (1, 2, 3, 4, 5))
);
