-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "amount" DECIMAL(16, 2) CHECK (amount > 0),
  "ratio" DECIMAL(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  "score" INTEGER CHECK (score >= 0)
);
