
CREATE TABLE "user" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" NUMBER(16, 2) NOT NULL CHECK (amount > 0),
  "ratio" NUMBER(20, 6) NOT NULL CHECK (ratio >= 0 AND ratio <= 100),
  "score" NUMBER(10) NOT NULL CHECK (score >= 0)
);
