-- Generated by rune 0.75.0

CREATE TABLE "user" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" NUMBER(16, 2) CHECK (amount > 0),
  "ratio" NUMBER(20, 6) CHECK (ratio >= 0 AND ratio <= 100),
  "score" NUMBER(10) CHECK (score >= 0)
);
