-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL
);

CREATE TABLE "coupon" (
  "id" NUMBER(10) PRIMARY KEY
);

CREATE TABLE "order" (
  "id" NUMBER(10) PRIMARY KEY,
  "user_id" NUMBER(10),
  "coupon_id" NUMBER(10),
  "amount" NUMBER(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("coupon_id") REFERENCES "coupon"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
