-- Generated by rune 0.332.0 [sqlite]

CREATE TABLE "users" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "org" INTEGER NOT NULL,
  "name" varchar(32) NOT NULL
);
-- @sym id n
-- @sym org n
-- @sym name s32

CREATE TABLE "memberships" (
  "user_id" INTEGER NOT NULL,
  "org_id" INTEGER NOT NULL,
  FOREIGN KEY ("user_id", "org_id") REFERENCES "users"("id", "org") ON UPDATE CASCADE
);
-- @sym user_id n
-- @sym org_id n
