-- Generated by rune 0.332.0 [pg]

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "users" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "org" integer NOT NULL,
  "name" varchar(32) NOT NULL
);

CREATE TABLE "memberships" (
  "user_id" integer NOT NULL,
  "org_id" integer NOT NULL,
  FOREIGN KEY ("user_id", "org_id") REFERENCES "users"("id", "org") ON UPDATE CASCADE
);
