-- Generated by rune 0.332.0 [mysql]

CREATE DATABASE `demo` CHARACTER SET utf8mb4;

CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `org` int NOT NULL,
  `name` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `memberships` (
  `user_id` int NOT NULL,
  `org_id` int NOT NULL,
  FOREIGN KEY (`user_id`, `org_id`) REFERENCES `users`(`id`, `org`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
