-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "uuid" VARCHAR2(36) NOT NULL,
  "email" VARCHAR2(128) NOT NULL,
  "name" VARCHAR2(64) NOT NULL,
  "ip" VARCHAR2(255)
);
