
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "uuid" VARCHAR(36) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "ip" VARCHAR(255) NOT NULL
);
