
CREATE TABLE "products" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "price" INTEGER NOT NULL,
  "qty" INTEGER NOT NULL,
  "total" INTEGER NOT NULL GENERATED ALWAYS AS (price qty) VIRTUAL,
  "tax" INTEGER NOT NULL GENERATED ALWAYS AS (price 0.1) STORED
);
