-- Generated by rune 0.69.0

CREATE TABLE "products" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(255),
  "price" INTEGER,
  "qty" INTEGER,
  "total" INTEGER GENERATED ALWAYS AS (price * qty) VIRTUAL,
  "tax" INTEGER GENERATED ALWAYS AS (price * 0.1) STORED
);
