-- Generated by rune 0.57.0

CREATE DATABASE "generated_columns" ENCODING 'UTF8';

CREATE TABLE "products" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "price" integer,
  "qty" integer,
  "total" integer GENERATED ALWAYS AS (price * qty) STORED,
  "tax" integer GENERATED ALWAYS AS (price * 0.1) STORED
);
