-- Generated by rune 0.75.0

CREATE TABLE "products" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(255),
  "price" NUMBER(10),
  "qty" NUMBER(10),
  "total" NUMBER(10) GENERATED ALWAYS AS (price * qty) VIRTUAL,
  "tax" NUMBER(10) GENERATED ALWAYS AS (price * 0.1) STORED
);
