-- Generated by rune 0.35.0

CREATE DATABASE `generated_columns` CHARACTER SET utf8mb4;

CREATE TABLE `products` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255),
  `price` int,
  `qty` int,
  `total` int GENERATED ALWAYS AS (price * qty) VIRTUAL,
  `tax` int GENERATED ALWAYS AS (price * 0.1) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
