# Generated by rune 0.65.0
# Do not edit manually.

enum roleType {
  admin
  user
  guest
}

type users {
  id: ID
  name: String
  role: roleType
}

input usersInput {
  name: String
  role: roleType
}

type Query {
  """Fetch a users by ID."""
  user(id: ID!): users
  """List all users records."""
  usersList(limit: Int, offset: Int): [users!]!
}

type Mutation {
  """Create a new users."""
  createUser(input: usersInput!): User!
  """Update an existing users."""
  updateUser(id: ID!, input: usersInput!): User!
  """Delete a users."""
  deleteUser(id: ID!): Boolean!
}
