-- Generated by rune 0.75.0

CREATE TABLE "users" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32)
);

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, name FROM users WHERE active = 1;
