-- Generated by rune 0.69.0

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32)
);

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, name FROM users WHERE active = 1;
