-- Generated by rune 0.75.0

CREATE TABLE "users" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(32)
);

CREATE TABLE "orders" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" NUMBER(10),
  "amount" NUMBER(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
);
