-- Generated by rune 0.69.0

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32),
  "role" VARCHAR(255) CHECK ("role" IN ('admin', 'user', 'guest'))
);
