# Generated by rune 0.65.0
# Do not edit manually.

type users {
  id: ID
  name: String
}

type active_users {
  # View columns (inspect the SQL query for details)
  _placeholder: String
}

input usersInput {
  name: String
}

type Query {
  """Fetch a users by ID."""
  user(id: ID!): users
  """List all users records."""
  usersList(limit: Int, offset: Int): [users!]!
  """Fetch from view active_users."""
  active_users: [active_users!]!
}

type Mutation {
  """Create a new users."""
  createUser(input: usersInput!): User!
  """Update an existing users."""
  updateUser(id: ID!, input: usersInput!): User!
  """Delete a users."""
  deleteUser(id: ID!): Boolean!
}
