-- Generated by rune 0.69.0

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32)
);

CREATE TABLE "orders" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER,
  "amount" DECIMAL(16, 2),
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
);
