-- Generated by rune 0.66.0

CREATE TABLE "order" (
  "id" NUMBER(10) PRIMARY KEY,
  "user_id" NUMBER(10) CHECK (user_id = user.id),
  "total" DATE,
  "status" VARCHAR2(255) CHECK (status IN ('draft', 'pending', 'done')),
  INDEX "idx_user_id" ("user_id"),
  INDEX "idx_status" ("status")
);
COMMENT ON TABLE "order" IS '订单表';
CREATE INDEX "idx_order_user_id" ON "order" ("user_id");
CREATE INDEX "idx_order_status" ON "order" ("status");

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(255)
);
COMMENT ON TABLE "user" IS '用户表';
