-- Generated by rune 0.75.0

CREATE TABLE "t" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(255) NOT NULL,
  "email" VARCHAR2(255) NOT NULL,
  "status" NUMBER(1),
  UNIQUE INDEX "uk_email" ("email")
);
COMMENT ON TABLE "t" IS '用户表';
