-- Generated by rune 0.82.0

CREATE TABLE "order" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" NUMBER(10) NOT NULL CHECK (user_id = user.id),
  "total" DATE NOT NULL,
  "status" VARCHAR2(255) NOT NULL CHECK (status IN ('draft', 'pending', 'done')),
  INDEX "idx_user_id" ("user_id"),
  INDEX "idx_status" ("status")
);
COMMENT ON TABLE "order" IS '订单表';

CREATE TABLE "user" (
  "id" NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR2(255) NOT NULL
);
COMMENT ON TABLE "user" IS '用户表';
