-- Generated by rune 0.69.0

CREATE TABLE "t" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "status" BOOLEAN,
  UNIQUE INDEX "uk_email" ("email")
);
COMMENT ON TABLE "t" IS '用户表';
