-- Generated by rune 0.66.0

CREATE TABLE "post" (
  "title" VARCHAR2(255) NOT NULL
);

CREATE TABLE "comment" (
  "post_id" NUMBER(10) CHECK (post_id = post.id),
  "body" VARCHAR2(255),
  INDEX "idx_post_id" ("post_id")
);
CREATE INDEX "idx_comment_post_id" ON "comment" ("post_id");
