-- Generated by rune 0.82.0

CREATE TABLE "post" (
  "title" VARCHAR2(255) NOT NULL
);

CREATE TABLE "comment" (
  "post_id" NUMBER(10) NOT NULL CHECK (post_id = post.id),
  "body" VARCHAR2(255) NOT NULL,
  INDEX "idx_post_id" ("post_id")
);
