-- Generated by rune 0.69.0

CREATE TABLE "post" (
  "title" VARCHAR(255) NOT NULL
);

CREATE TABLE "comment" (
  "post_id" INTEGER CHECK (post_id = post.id),
  "body" VARCHAR(255),
  INDEX "idx_post_id" ("post_id")
);
CREATE INDEX "idx_comment_post_id" ON "comment" ("post_id");
