
CREATE TABLE "t" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "status" BOOLEAN NOT NULL,
  UNIQUE INDEX "uk_email" ("email")
);
COMMENT ON TABLE "t" IS '用户表';
