-- Migration: schema diff
-- Generated by rune 0.37.0 migrate

BEGIN;

ALTER TABLE "user"
ADD UNIQUE ("email"),
-- NOTE: CREATE INDEX needed for 'idx_name' (not supported via ALTER TABLE in PG)
;
COMMIT;
