-- Migration: schema diff
-- Generated by rune 0.48.0 migrate

BEGIN;

ALTER TABLE "t"
-- WARNING: MODIFY COLUMN not supported in SQLite; requires table recreation
,
-- WARNING: MODIFY COLUMN not supported in SQLite; requires table recreation
,
ADD COLUMN "email" varchar(128);
COMMIT;
