-- Migration: schema diff
-- Generated by rune 0.46.0 migrate

BEGIN;

CREATE TABLE "post" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "title" varchar(128) NOT NULL
);


ALTER TABLE "user"
ALTER COLUMN "name" TYPE varchar(64) NOT NULL;
COMMIT;
