-- Generated by rune 0.44.0

CREATE DATABASE "mydb" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32) NOT NULL,
  "email" varchar(64) NOT NULL,
  UNIQUE ("email")
);
