-- Generated by rune 0.329.0 [sqlite]

CREATE TABLE "users" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" varchar(100) NOT NULL,
  "email" varchar(128) NOT NULL,
  UNIQUE ("email")
);
-- @sym id n
-- @sym name s100
-- @sym email s128

CREATE TABLE "orders" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER NOT NULL,
  "amount" NUMERIC(16, 2) NOT NULL CHECK (amount > 0),
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
);
-- @sym id n
-- @sym user_id n
-- @sym amount m
