-- Generated by rune 0.34.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" varchar(32) NOT NULL,
  "created" TEXT
);
-- @sym id n
-- @sym name s32
-- @sym created t

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "amount" NUMERIC(16, 2),
  "created" TEXT
);
-- @sym id n
-- @sym amount m
-- @sym created t
