-- Generated by rune

CREATE TABLE "products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT,
  "price" INTEGER,
  "qty" INTEGER,
  "total" INTEGER GENERATED ALWAYS AS (price * qty) VIRTUAL,
  "tax" INTEGER GENERATED ALWAYS AS (price * 0.1) STORED
);
-- @sym id n
-- @sym price n
-- @sym qty n
-- @sym total n
-- @sym tax n
