-- Generated by rune 0.49.0

CREATE TABLE "user_role" (
  "user_id" INTEGER NOT NULL PRIMARY KEY,
  "role_id" INTEGER NOT NULL PRIMARY KEY,
  "granted" TEXT
);
-- @sym user_id n
-- @sym role_id n
-- @sym granted t
