-- Generated by rune 0.57.0

CREATE TABLE "settings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "enabled" INTEGER,
  "config" TEXT,
  "metadata" TEXT,
  "name" varchar(32) NOT NULL
);
-- @sym id n
-- @sym enabled b
-- @sym config j
-- @sym metadata J
-- @sym name s32
