-- Generated by rune 0.69.0

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "user_id" INTEGER,
  "amount" DECIMAL(16, 2)
);

CREATE OR REPLACE VIEW "user_summary" AS
SELECT u.id, u.name, COUNT(o.id) AS order_count FROM user u LEFT JOIN order o ON u.id = o.user_id GROUP BY u.id;

CREATE OR REPLACE VIEW "expensive_orders" AS
SELECT * FROM order WHERE amount > 1000;
