-- Generated by rune 0.36.0

CREATE DATABASE "demo" ENCODING 'UTF8';

CREATE TABLE "user" (
  "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" varchar(32) NOT NULL
);

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, name FROM user WHERE active = 1;
