-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL
);

CREATE TABLE "order" (
  "id" NUMBER(10) PRIMARY KEY,
  "user_id" NUMBER(10),
  "amount" NUMBER(16, 2)
);

CREATE OR REPLACE VIEW "user_summary" AS
SELECT u.id, u.name, COUNT(o.id) AS order_count FROM user u LEFT JOIN order o ON u.id = o.user_id GROUP BY u.id;

CREATE OR REPLACE VIEW "expensive_orders" AS
SELECT * FROM order WHERE amount > 1000;
