-- Generated by rune 0.66.0

CREATE TABLE "user" (
  "id" NUMBER(10) PRIMARY KEY,
  "name" VARCHAR2(32) NOT NULL
);

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, name FROM user WHERE active = 1;
