-- Generated by rune 0.320.0 [mssql]

CREATE TABLE [user] (
  [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [name] NVARCHAR(32) NOT NULL
);

CREATE VIEW [active_users] AS
SELECT id, name FROM user WHERE active = 1;
