
CREATE TABLE "user" (
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(32) NOT NULL
);

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, name FROM user WHERE active = 1;
