
CREATE DATABASE "test_warn" ENCODING 'UTF8';

CREATE TABLE "warn_table" (
  "name" varchar(32) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "tag" varchar(255) NOT NULL,
  "count" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "balance" numeric(16, 2) NOT NULL
);
