
CREATE TABLE "warn_table" (
  "name" VARCHAR(32) NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "tag" VARCHAR(255) NOT NULL,
  "count" INTEGER NOT NULL,
  "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "balance" DECIMAL(16, 2) NOT NULL
);
