const std = @import("std");
const ast_mod = @import("../types/ast.zig");
const dialect_mod = @import("../dialect/dialect.zig");
const dialect_enum = @import("../dialect/enum.zig");
const typed_ast_mod = @import("../types/typed_ast.zig");
const columns_mod = @import("columns.zig");
const indexes_mod = @import("indexes.zig");
const version = @import("../version.zig");
const Writer = std.Io.Writer;

pub const Dialect = dialect_enum.Dialect;

pub const Codegen = struct {
    alloc: std.mem.Allocator,
    dialect: Dialect,
    backend: dialect_mod.DialectBackend,

    pub fn init(alloc: std.mem.Allocator, dialect: Dialect) Codegen {
        return .{
            .alloc = alloc,
            .dialect = dialect,
            .backend = dialect_mod.getBackend(dialect),
        };
    }

    // ─── TypedAst API (sole codegen path) ───────────────────────

    /// Generate SQL DDL from a TypedAst. Returns the complete SQL string.
    pub fn generateFromTypedAst(self: *Codegen, typed: typed_ast_mod.TypedAst) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;

        try w.print("-- Generated by rune {s}\n\n", .{version.VERSION});

        if (typed.schema_name) |name| {
            try self.backend.emitCreateDatabase(w, name, typed.schema_charset);
        }

        // Interleave tables, views, and sql_comments by line number
        var ti: usize = 0;
        var vi: usize = 0;
        var ci: usize = 0;
        while (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
            const table_line = if (ti < typed.tables.len) typed.tables[ti].line_no else std.math.maxInt(usize);
            const view_line = if (vi < typed.views.len) typed.views[vi].line_no else std.math.maxInt(usize);
            const comment_line = if (ci < typed.sql_comments.len) typed.sql_comments[ci].line_no else std.math.maxInt(usize);

            const min_line = @min(table_line, view_line, comment_line);

            if (comment_line == min_line) {
                try w.writeAll(typed.sql_comments[ci].text);
                try w.writeAll("\n");
                ci += 1;
            } else if (view_line == min_line) {
                try self.generateTypedView(w, typed.views[vi]);
                vi += 1;
                if (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            } else if (table_line == min_line) {
                try self.generateTypedTable(w, typed.tables[ti]);
                ti += 1;
                if (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
                    try w.writeAll("\n");
                }
            }
        }

        try w.flush();
        return try aw.toOwnedSlice();
    }

    /// Emit a full CREATE TABLE statement for one table to the given writer.
    /// Used by both forward codegen (generateFromTypedAst) and migration generation.
    pub fn generateTypedTable(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable) !void {
        try w.writeAll("CREATE TABLE ");
        try self.backend.quoteIdent(w, table.name);
        try w.writeAll(" (\n");

        var needs_comma = false;

        try emitColumnDefs(self, w, table, &needs_comma);
        try indexes_mod.emitInlineIndexes(self.backend, w, table, &needs_comma);
        for (table.indexes) |idx| {
            try self.backend.emitIndex(w, idx, &needs_comma);
        }
        try emitConstraints(self, w, table, &needs_comma);

        if (needs_comma) try w.writeAll("\n");

        try self.backend.emitTableFooter(w, table.engine, null, table.comment);
        try emitTableMetadata(self, w, table);
        try indexes_mod.emitStandaloneIndexes(self.backend, w, table);
        try indexes_mod.emitInlineColumnStandaloneIndexes(self.backend, w, table);
    }

    fn emitColumnDefs(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable, needs_comma: *bool) !void {
        for (table.columns) |col| {
            if (needs_comma.*) try w.writeAll(",\n");
            needs_comma.* = true;
            try w.writeAll("  ");
            try columns_mod.emitColumnDef(self.backend, w, col);
        }
    }

    fn emitConstraints(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable, needs_comma: *bool) !void {
        for (table.fks) |fk| {
            if (needs_comma.*) try w.writeAll(",\n");
            needs_comma.* = true;
            try w.writeAll("  ");
            try self.backend.emitForeignKey(w, fk);
        }
    }

    fn emitTableMetadata(self: Codegen, w: *Writer, table: typed_ast_mod.TypedTable) !void {
        if (table.comment) |c| {
            try self.backend.emitTableComment(w, table.name, c);
        }
        for (table.columns) |col| {
            if (col.comment) |c| {
                try self.backend.emitColumnComment(w, table.name, col.name, c);
            }
        }
        for (table.columns) |col| {
            if (col.ss_symbol) |sym| {
                try self.backend.emitTypeMetadata(w, col.name, sym);
            }
        }
    }

    /// Emit a CREATE VIEW statement.
    pub fn generateTypedView(self: Codegen, w: *Writer, view: typed_ast_mod.TypedView) !void {
        // Build the full query, combining UNION/INTERSECT/EXCEPT parts
        if (view.union_op) |op| {
            const second = view.second_query orelse "";
            const op_str: []const u8 = switch (op) {
                .union_all => " UNION ALL ",
                .union_distinct => " UNION ",
                .intersect => " INTERSECT ",
                .except => " EXCEPT ",
            };
            var buf = std.Io.Writer.Allocating.init(self.alloc);
            try buf.writer.writeAll(view.query);
            try buf.writer.writeAll(op_str);
            try buf.writer.writeAll(second);
            const full_query = try buf.toOwnedSlice();
            try self.backend.emitCreateView(w, view.name, full_query);
        } else {
            try self.backend.emitCreateView(w, view.name, view.query);
        }
        if (view.comment) |c| {
            try self.backend.emitTableComment(w, view.name, c);
        }
    }

    /// Render a single column definition (shared by CREATE TABLE and ALTER TABLE paths).
    /// When skip_name is true, the column name is not emitted (used by PG ALTER COLUMN TYPE).
    pub fn emitColumnDef(self: Codegen, w: *Writer, col: typed_ast_mod.TypedColumn) !void {
        return columns_mod.emitColumnDef(self.backend, w, col);
    }

    pub fn emitColumnDefEx(self: Codegen, w: *Writer, col: typed_ast_mod.TypedColumn, skip_name: bool) !void {
        return columns_mod.emitColumnDefEx(self.backend, w, col, skip_name);
    }
};

// ─── Diagnostic ──────────────────────────────────────────────

pub fn diagnosticTrace(typed: typed_ast_mod.TypedAst) void {
    std.debug.print("=== [Stage 4: Codegen] ===\n\n", .{});

    var column_count: usize = 0;
    var fk_count: usize = 0;
    var index_count: usize = 0;

    for (typed.tables) |table| {
        column_count += table.columns.len;
        fk_count += table.fks.len;
        index_count += table.indexes.len;
    }

    std.debug.print("Tables:    {d}\n", .{typed.tables.len});
    std.debug.print("Columns:   {d}\n", .{column_count});
    std.debug.print("Views:     {d}\n", .{typed.views.len});
    std.debug.print("FKs:       {d}\n", .{fk_count});
    std.debug.print("Indexes:   {d}\n\n", .{index_count});
}

// ─── Shared helpers (dialect-independent) ──────────────────────

/// Render a CHECK constraint expression from a field name and CheckConstraint.
/// Handles range, in_list, and comparison expressions.
pub fn emitCheckExpr(w: *Writer, field_name: []const u8, ck: ast_mod.CheckConstraint) !void {
    switch (ck.kind) {
        .range => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            const low = std.mem.trim(u8, parts.next() orelse "", " ");
            const high = std.mem.trim(u8, parts.next() orelse "", " ");
            try w.print("{s} BETWEEN {s} AND {s}", .{ field_name, low, high });
        },
        .range_upper_exclusive => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            const low = std.mem.trim(u8, parts.next() orelse "", " ");
            const high = std.mem.trim(u8, parts.next() orelse "", " ");
            try w.print("{s} >= {s} AND {s} < {s}", .{ field_name, low, field_name, high });
        },
        .range_lower_exclusive => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            const low = std.mem.trim(u8, parts.next() orelse "", " ");
            const high = std.mem.trim(u8, parts.next() orelse "", " ");
            try w.print("{s} > {s} AND {s} <= {s}", .{ field_name, low, field_name, high });
        },
        .range_both_exclusive => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            const low = std.mem.trim(u8, parts.next() orelse "", " ");
            const high = std.mem.trim(u8, parts.next() orelse "", " ");
            try w.print("{s} > {s} AND {s} < {s}", .{ field_name, low, field_name, high });
        },
        .in_list => {
            try w.print("{s} IN (", .{field_name});
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            var first = true;
            while (parts.next()) |part| {
                const trimmed = std.mem.trim(u8, part, " ");
                if (trimmed.len == 0) continue;
                if (!first) try w.writeAll(", ");
                first = false;
                const is_num = blk: {
                    _ = std.fmt.parseFloat(f64, trimmed) catch break :blk false;
                    break :blk true;
                };
                if (is_num) {
                    try w.print("{s}", .{trimmed});
                } else {
                    const val = if (trimmed.len >= 2 and trimmed[0] == '\'' and trimmed[trimmed.len - 1] == '\'')
                        trimmed[1 .. trimmed.len - 1]
                    else
                        trimmed;
                    try w.print("'{s}'", .{val});
                }
            }
            try w.writeAll(")");
        },
        .comparison => {
            var parts = std.mem.splitScalar(u8, ck.expr, ',');
            var first = true;
            while (parts.next()) |part| {
                const trimmed = std.mem.trim(u8, part, " ");
                if (trimmed.len == 0) continue;
                if (!first) try w.writeAll(" AND ");
                first = false;
                if (trimmed[0] == '>' and trimmed.len > 1 and trimmed[1] == '=') {
                    try w.print("{s} >= {s}", .{ field_name, trimmed[2..] });
                } else if (trimmed[0] == '<' and trimmed.len > 1 and trimmed[1] == '=') {
                    try w.print("{s} <= {s}", .{ field_name, trimmed[2..] });
                } else if (trimmed[0] == '>') {
                    try w.print("{s} > {s}", .{ field_name, trimmed[1..] });
                } else if (trimmed[0] == '<') {
                    try w.print("{s} < {s}", .{ field_name, trimmed[1..] });
                } else if (trimmed[0] == '=') {
                    try w.print("{s} = {s}", .{ field_name, trimmed[1..] });
                } else {
                    try w.print("{s} = {s}", .{ field_name, trimmed });
                }
            }
        },
    }
}
