const std = @import("std");
const streaming = @import("streaming.zig");
const typed_ast_mod = @import("../types/typed_ast.zig");
const codegen = @import("../codegen/codegen.zig");
const test_helpers = @import("../semantic/test_helpers.zig");

const testing = std.testing;
const makeTestColumn = test_helpers.makeTestColumn;

fn makeTestTable(name: []const u8, cols: []const typed_ast_mod.TypedColumn) typed_ast_mod.TypedTable {
    return .{
        .name = name,
        .comment = null,
        .engine = null,
        .columns = cols,
        .fks = &.{},
        .indexes = &.{},
        .line_no = 1,
    };
}

test "streaming: single table MySQL" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 2);
    cols[0] = makeTestColumn("id", .int);
    cols[0].flags.primary_key = true;
    cols[0].flags.auto_increment = true;
    cols[1] = makeTestColumn("name", .{ .passthrough = "varchar(32)" });

    const table = makeTestTable("users", cols);
    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var sc = streaming.StreamingCodegen.init(alloc, .mysql);
    const result = try sc.generateStreaming(typed);

    try testing.expectEqual(@as(usize, 1), result.table_count);
    try testing.expectEqual(@as(usize, 1), result.tables.len);
    try testing.expect(std.mem.eql(u8, result.tables[0].name, "users"));
    try testing.expect(std.mem.indexOf(u8, result.tables[0].sql, "CREATE TABLE `users`") != null);
}

test "streaming: multi-table output order preserved" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    const cols1 = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols1[0] = makeTestColumn("id", .int);
    cols1[0].flags.primary_key = true;

    const cols2 = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols2[0] = makeTestColumn("id", .int);
    cols2[0].flags.primary_key = true;

    const table1 = makeTestTable("alpha", cols1);
    const table2 = makeTestTable("beta", cols2);
    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{ table1, table2 });
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var sc = streaming.StreamingCodegen.init(alloc, .mysql);
    const result = try sc.generateStreaming(typed);

    try testing.expectEqual(@as(usize, 2), result.table_count);
    try testing.expectEqual(@as(usize, 2), result.tables.len);
    try testing.expect(std.mem.eql(u8, result.tables[0].name, "alpha"));
    try testing.expect(std.mem.eql(u8, result.tables[1].name, "beta"));
}

test "streaming: formatStreamingResult includes header" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    const cols = try alloc.alloc(typed_ast_mod.TypedColumn, 1);
    cols[0] = makeTestColumn("id", .int);
    cols[0].flags.primary_key = true;

    const table = makeTestTable("t1", cols);
    const tables = try alloc.dupe(typed_ast_mod.TypedTable, &.{table});
    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = tables,
        .views = &.{},
        .sql_comments = &.{},
    };

    var sc = streaming.StreamingCodegen.init(alloc, .mysql);
    const result = try sc.generateStreaming(typed);
    const sql = try streaming.formatStreamingResult(alloc, &result, .mysql);

    try testing.expect(std.mem.indexOf(u8, sql, "-- Generated by rune") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "[mysql]") != null);
    try testing.expect(std.mem.indexOf(u8, sql, "CREATE TABLE `t1`") != null);
}

test "streaming: empty schema produces header only" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    const typed = typed_ast_mod.TypedAst{
        .schema_name = null,
        .schema_charset = null,
        .tables = &.{},
        .views = &.{},
        .sql_comments = &.{},
    };

    var sc = streaming.StreamingCodegen.init(alloc, .mysql);
    const result = try sc.generateStreaming(typed);

    try testing.expectEqual(@as(usize, 0), result.table_count);
    try testing.expectEqual(@as(usize, 0), result.tables.len);

    const sql = try streaming.formatStreamingResult(alloc, &result, .mysql);
    try testing.expect(std.mem.indexOf(u8, sql, "-- Generated by rune") != null);
}
