const std = @import("std");
const codegen = @import("../codegen/codegen.zig");
const typed_ast_mod = @import("../types/typed_ast.zig");
const version = @import("../version.zig");

// ─── Streaming Compilation ─────────────────────────────────────

/// Result from streaming compilation — holds per-table SQL output.
pub const StreamingResult = struct {
    /// SQL for each table, in order of generation.
    tables: []TableOutput,
    /// Total SQL size in bytes.
    total_size: usize,
    /// Number of tables processed.
    table_count: usize,

    pub const TableOutput = struct {
        name: []const u8,
        sql: []const u8,
    };
};

/// Streaming codegen that emits each table's SQL immediately.
/// Useful for large schemas where you want to start processing output
/// before the entire schema is compiled.
pub const StreamingCodegen = struct {
    alloc: std.mem.Allocator,
    dialect: codegen.Dialect,
    cg: codegen.Codegen,

    pub fn init(alloc: std.mem.Allocator, dialect: codegen.Dialect) StreamingCodegen {
        return .{
            .alloc = alloc,
            .dialect = dialect,
            .cg = codegen.Codegen.init(alloc, dialect),
        };
    }

    /// Generate SQL for a single table and return it.
    /// This allows incremental processing of large schemas.
    pub fn generateTable(self: StreamingCodegen, table: typed_ast_mod.TypedTable) ![]const u8 {
        var aw = std.Io.Writer.Allocating.init(self.alloc);
        const w = &aw.writer;

        try self.cg.generateTypedTable(w, table);

        try w.flush();
        return try aw.toOwnedSlice();
    }

    /// Generate complete SQL with streaming output.
    /// Each table's SQL is returned separately, enabling incremental processing.
    pub fn generateStreaming(self: StreamingCodegen, typed: typed_ast_mod.TypedAst) !StreamingResult {
        var total_size: usize = 0;
        var tables = try std.ArrayList(StreamingResult.TableOutput).initCapacity(self.alloc, typed.tables.len);

        // Emit header
        const header = try std.fmt.allocPrint(self.alloc, "-- Generated by rune {s} [{s}]\n\n", .{ version.VERSION, @tagName(self.dialect) });

        // Track views and comments for interleaving
        var ti: usize = 0;
        var vi: usize = 0;
        var ci: usize = 0;

        while (ti < typed.tables.len or vi < typed.views.len or ci < typed.sql_comments.len) {
            const table_line = if (ti < typed.tables.len) typed.tables[ti].line_no else std.math.maxInt(usize);
            const view_line = if (vi < typed.views.len) typed.views[vi].line_no else std.math.maxInt(usize);
            const comment_line = if (ci < typed.sql_comments.len) typed.sql_comments[ci].line_no else std.math.maxInt(usize);

            const min_line = @min(table_line, view_line, comment_line);

            if (comment_line == min_line) {
                // Skip comments in streaming mode (they're part of the full output)
                ci += 1;
            } else if (view_line == min_line) {
                // Skip views in streaming mode
                vi += 1;
            } else if (table_line == min_line) {
                const sql = try self.generateTable(typed.tables[ti]);
                try tables.append(self.alloc, .{
                    .name = typed.tables[ti].name,
                    .sql = sql,
                });
                total_size += sql.len;
                ti += 1;
            }
        }

        return .{
            .tables = try tables.toOwnedSlice(self.alloc),
            .total_size = total_size + header.len,
            .table_count = typed.tables.len,
        };
    }
};

/// Format streaming result as complete SQL.
pub fn formatStreamingResult(alloc: std.mem.Allocator, result: *const StreamingResult, dialect: codegen.Dialect) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    try w.print("-- Generated by rune {s} [{s}]\n\n", .{ version.VERSION, @tagName(dialect) });

    for (result.tables, 0..) |table, i| {
        try w.writeAll(table.sql);
        if (i < result.tables.len - 1) {
            try w.writeAll("\n");
        }
    }

    try w.flush();
    return try aw.toOwnedSlice();
}
