const std = @import("std");
const col = @import("column.zig");
const sp = @import("../parser/sql_parser.zig");

const testing = std.testing;
const isInlineIndex = col.isInlineIndex;
const isAutoGeneratedName = col.isAutoGeneratedName;

// ─── Inline Tests ──────────────────────────────────────────────

test "isInlineIndex uk_* matches" {
    const idx = sp.SqlIndex{
        .kind = .unique,
        .name = "uk_email",
        .fields = &.{"email"},
        .descending = &.{},
    };
    try std.testing.expect(isInlineIndex(idx));
}

test "isInlineIndex idx_* matches" {
    const idx = sp.SqlIndex{
        .kind = .regular,
        .name = "idx_name",
        .fields = &.{"name"},
        .descending = &.{},
    };
    try std.testing.expect(isInlineIndex(idx));
}

test "isInlineIndex multi-field -> false" {
    const idx = sp.SqlIndex{
        .kind = .unique,
        .name = "uk_a_b",
        .fields = &.{ "a", "b" },
        .descending = &.{},
    };
    try std.testing.expect(!isInlineIndex(idx));
}

test "isInlineIndex name mismatch -> false" {
    const idx = sp.SqlIndex{
        .kind = .unique,
        .name = "uk_email",
        .fields = &.{"name"},
        .descending = &.{},
    };
    try std.testing.expect(!isInlineIndex(idx));
}

test "isInlineIndex primary_key -> false" {
    const idx = sp.SqlIndex{
        .kind = .primary_key,
        .name = "",
        .fields = &.{"id"},
        .descending = &.{},
    };
    try std.testing.expect(!isInlineIndex(idx));
}

test "isInlineIndex PG table-prefixed uk matches" {
    const idx = sp.SqlIndex{
        .kind = .unique,
        .name = "uk_user_email",
        .fields = &.{"email"},
        .descending = &.{},
    };
    try std.testing.expect(isInlineIndex(idx));
}

test "isInlineIndex PG table-prefixed idx matches" {
    const idx = sp.SqlIndex{
        .kind = .regular,
        .name = "idx_t_name",
        .fields = &.{"name"},
        .descending = &.{},
    };
    try std.testing.expect(isInlineIndex(idx));
}

test "isAutoGeneratedName idx_field matches" {
    const idx = sp.SqlIndex{
        .kind = .regular,
        .name = "idx_name",
        .fields = &.{"name"},
        .descending = &.{},
    };
    try std.testing.expect(isAutoGeneratedName(idx));
}

test "isAutoGeneratedName uk_field matches" {
    const idx = sp.SqlIndex{
        .kind = .unique,
        .name = "uk_email",
        .fields = &.{"email"},
        .descending = &.{},
    };
    try std.testing.expect(isAutoGeneratedName(idx));
}

test "isAutoGeneratedName multi-field matches" {
    const idx = sp.SqlIndex{
        .kind = .regular,
        .name = "idx_a_b",
        .fields = &.{ "a", "b" },
        .descending = &.{},
    };
    try std.testing.expect(isAutoGeneratedName(idx));
}

test "isAutoGeneratedName custom name -> false" {
    const idx = sp.SqlIndex{
        .kind = .regular,
        .name = "my_index",
        .fields = &.{"name"},
        .descending = &.{},
    };
    try std.testing.expect(!isAutoGeneratedName(idx));
}

test "isAutoGeneratedName fulltext -> false" {
    const idx = sp.SqlIndex{
        .kind = .fulltext,
        .name = "ft_body",
        .fields = &.{"body"},
        .descending = &.{},
    };
    try std.testing.expect(!isAutoGeneratedName(idx));
}
