const std = @import("std");
const codegen = @import("../codegen/codegen.zig");

// ─── SQL Dialect Detection ─────────────────────────────────────
//
// Auto-detects SQL dialect from content patterns using weighted scoring.
// Each pattern match adds weight to the corresponding dialect score.
// Highest score wins; ties default to MySQL.
//
// Supports: MySQL, PostgreSQL, SQLite, MSSQL, Oracle, Db2.
//
// Matching discipline (v0.335.0): patterns are matched against a copy of the
// input with SQL comments (`--`, `/* */`) blanked out, and every match must
// sit on non-identifier boundaries — a `-- RESTRICT` comment must not score
// SQLite's STRICT, and an identifier containing "bit" must not score
// MSSQL's BIT.

fn isIdentChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or c == '_';
}

/// True when `needle` occurs in `haystack` with non-identifier characters
/// (or string edges) on both sides. Punctuation within multi-word patterns
/// (e.g. "ENGINE=", "KEY `", "GO\n") passes the boundary test trivially.
fn hasBoundedPattern(haystack: []const u8, needle: []const u8) bool {
    var start: usize = 0;
    while (std.mem.indexOfPos(u8, haystack, start, needle)) |i| {
        const before_ok = i == 0 or !isIdentChar(haystack[i - 1]);
        const end = i + needle.len;
        const after_ok = end >= haystack.len or !isIdentChar(haystack[end]);
        if (before_ok and after_ok) return true;
        start = i + 1;
    }
    return false;
}

/// Copy of `sql` with comment regions replaced by spaces (positions and
/// therefore word boundaries preserved): `-- …\n` line comments and
/// `/* … */` block comments. String literals ('…', "…", `…`) are tracked so
/// a `--` inside a value does not open a phantom comment.
fn blankComments(alloc: std.mem.Allocator, sql: []const u8) ![]u8 {
    const out = try alloc.alloc(u8, sql.len);
    @memcpy(out, sql);
    var i: usize = 0;
    while (i < out.len) {
        const c = out[i];
        if (c == '\'' or c == '"' or c == '`') {
            // Skip the literal body so quotes inside comments don't confuse
            // the scanner and comment markers inside literals stay put.
            i += 1;
            while (i < out.len) : (i += 1) {
                if (out[i] == c) {
                    if (c != '`' and i + 1 < out.len and out[i + 1] == c) {
                        i += 1; // doubled-quote escape ('' or "")
                    } else break;
                }
            }
            i += 1;
        } else if (c == '-' and i + 1 < out.len and out[i + 1] == '-') {
            while (i < out.len and out[i] != '\n') : (i += 1) out[i] = ' ';
        } else if (c == '/' and i + 1 < out.len and out[i + 1] == '*') {
            const close = std.mem.indexOfPos(u8, sql, i + 2, "*/") orelse out.len;
            @memset(out[i..@min(close + 2, out.len)], ' ');
            i = @min(close + 2, out.len);
        } else i += 1;
    }
    return out;
}

/// Auto-detect SQL dialect from content patterns using weighted scoring.
pub fn detectSqlDialect(alloc: std.mem.Allocator, sql: []const u8) codegen.Dialect {
    // Fast path: check for rune-generated header with dialect tag
    // e.g. "-- Generated by rune 0.87.0 [db2]"
    if (std.mem.startsWith(u8, sql, "-- Generated by rune ")) {
        // Find the first line (up to first \n or end of string)
        const first_line_end = std.mem.indexOf(u8, sql, "\n") orelse sql.len;
        const first_line = sql[0..first_line_end];
        if (std.mem.endsWith(u8, first_line, "]")) {
            if (std.mem.lastIndexOf(u8, first_line, " [")) |bracket_start| {
                const tag = first_line[bracket_start + 2 .. first_line.len - 1];
                if (std.mem.eql(u8, tag, "mysql")) return .mysql;
                if (std.mem.eql(u8, tag, "pg")) return .pg;
                if (std.mem.eql(u8, tag, "sqlite")) return .sqlite;
                if (std.mem.eql(u8, tag, "mssql")) return .mssql;
                if (std.mem.eql(u8, tag, "oracle")) return .oracle;
                if (std.mem.eql(u8, tag, "db2")) return .db2;
            }
        }
    }

    const body = blankComments(alloc, sql) catch sql;
    if (body.ptr == sql.ptr) return detectSqlDialectBody(body);
    defer alloc.free(body);
    return detectSqlDialectBody(body);
}

/// Score `body` (comments already blanked) against the per-dialect pattern table.
fn detectSqlDialectBody(body: []const u8) codegen.Dialect {
    var scores = [6]u8{ 0, 0, 0, 0, 0, 0 }; // mysql, pg, sqlite, mssql, oracle, db2

    // MySQL-specific patterns (high confidence)
    if (hasBoundedPattern(body, "ENGINE=")) scores[0] += 3;
    if (hasBoundedPattern(body, "CHARACTER SET")) scores[0] += 2;
    if (hasBoundedPattern(body, "DEFAULT CHARSET")) scores[0] += 2;
    if (hasBoundedPattern(body, "AUTO_INCREMENT")) scores[0] += 2;
    if (hasBoundedPattern(body, "UNSIGNED")) scores[0] += 2;
    if (hasBoundedPattern(body, "FULLTEXT INDEX")) scores[0] += 3;
    if (hasBoundedPattern(body, "COMMENT '")) scores[0] += 1;
    if (hasBoundedPattern(body, "ROW_FORMAT=")) scores[0] += 3;
    if (hasBoundedPattern(body, "COLLATE=")) scores[0] += 1;
    if (hasBoundedPattern(body, "UNIQUE KEY")) scores[0] += 2;
    if (hasBoundedPattern(body, "KEY `")) scores[0] += 2;
    if (hasBoundedPattern(body, "ON UPDATE CURRENT_TIMESTAMP")) scores[0] += 1;

    // PostgreSQL-specific patterns (high confidence)
    if (hasBoundedPattern(body, "GENERATED ALWAYS AS IDENTITY")) scores[1] += 2; // shared with Db2
    if (hasBoundedPattern(body, "COMMENT ON")) scores[1] += 2;
    if (hasBoundedPattern(body, "CREATE EXTENSION")) scores[1] += 3;
    if (hasBoundedPattern(body, "ENCODING=")) scores[1] += 2;
    if (hasBoundedPattern(body, "CREATE TYPE")) scores[1] += 2;
    if (hasBoundedPattern(body, "IF NOT EXISTS\n  (")) scores[1] += 1; // PG style serial
    if (hasBoundedPattern(body, "SERIAL")) scores[1] += 2;
    if (hasBoundedPattern(body, "BIGSERIAL")) scores[1] += 3;
    if (hasBoundedPattern(body, "bytea")) scores[1] += 2;
    if (hasBoundedPattern(body, "boolean")) scores[1] += 1;
    if (hasBoundedPattern(body, "jsonb")) scores[1] += 2;
    if (hasBoundedPattern(body, "timestamptz")) scores[1] += 3;

    // SQLite-specific patterns (high confidence)
    if (hasBoundedPattern(body, "AUTOINCREMENT")) scores[2] += 3;
    if (hasBoundedPattern(body, "INTEGER PRIMARY KEY")) scores[2] += 3;
    if (hasBoundedPattern(body, "WITHOUT ROWID")) scores[2] += 3;
    if (hasBoundedPattern(body, "STRICT")) scores[2] += 2;
    if (hasBoundedPattern(body, "CREATE TABLE \"")) scores[2] += 1;
    if (hasBoundedPattern(body, "ON CONFLICT")) scores[2] += 1;

    // MSSQL-specific patterns (high confidence)
    if (hasBoundedPattern(body, "IDENTITY(1,1)")) scores[3] += 3;
    if (hasBoundedPattern(body, "IDENTITY(1, 1)")) scores[3] += 3;
    if (hasBoundedPattern(body, "NVARCHAR")) scores[3] += 2;
    if (hasBoundedPattern(body, "[dbo]")) scores[3] += 3;
    if (hasBoundedPattern(body, "GO\n")) scores[3] += 2;
    if (hasBoundedPattern(body, "BIT")) scores[3] += 1;
    if (hasBoundedPattern(body, "DATETIME2")) scores[3] += 3;
    if (hasBoundedPattern(body, "NTEXT")) scores[3] += 3;
    if (hasBoundedPattern(body, "VARCHAR(MAX)")) scores[3] += 2;
    if (hasBoundedPattern(body, "VARBINARY(MAX)")) scores[3] += 3;

    // Oracle-specific patterns (high confidence)
    if (hasBoundedPattern(body, "VARCHAR2")) scores[4] += 3;
    if (hasBoundedPattern(body, "NUMBER(")) scores[4] += 2;
    if (hasBoundedPattern(body, "SYSDATE")) scores[4] += 3;
    if (hasBoundedPattern(body, "CREATE SEQUENCE")) scores[4] += 3;
    if (hasBoundedPattern(body, "CREATE TRIGGER")) scores[4] += 2;
    if (hasBoundedPattern(body, "CLOB")) scores[4] += 2;
    if (hasBoundedPattern(body, "BLOB")) scores[4] += 1;
    if (hasBoundedPattern(body, "NCLOB")) scores[4] += 3;
    if (hasBoundedPattern(body, "NVARCHAR2")) scores[4] += 3;
    if (hasBoundedPattern(body, "ENABLE")) scores[4] += 1;

    // Db2-specific patterns (high confidence)
    if (hasBoundedPattern(body, "GENERATED ALWAYS AS IDENTITY")) scores[5] += 3;
    if (hasBoundedPattern(body, "DECFLOAT")) scores[5] += 3;
    if (hasBoundedPattern(body, "GRAPHIC")) scores[5] += 3;
    if (hasBoundedPattern(body, "VARGRAPHIC")) scores[5] += 3;
    if (hasBoundedPattern(body, "GENERATED ALWAYS AS (")) scores[5] += 3;
    if (hasBoundedPattern(body, "SMALLINT")) scores[5] += 1;
    if (hasBoundedPattern(body, "BIGINT")) scores[5] += 1;
    if (hasBoundedPattern(body, "DATALINKS")) scores[5] += 3;
    if (hasBoundedPattern(body, "CHAR(16) FOR BIT DATA")) scores[5] += 3;
    if (hasBoundedPattern(body, "CHARACTER(16) FOR BIT DATA")) scores[5] += 3;
    if (hasBoundedPattern(body, "LONG VARCHAR")) scores[5] += 2;
    if (hasBoundedPattern(body, "NOT NULL WITH DEFAULT")) scores[5] += 2;

    // Determine winner (ties → MySQL)
    var best: usize = 0;
    for (scores, 0..) |s, i| {
        if (s > scores[best]) best = i;
    }

    return switch (best) {
        1 => .pg,
        2 => .sqlite,
        3 => .mssql,
        4 => .oracle,
        5 => .db2,
        else => .mysql,
    };
}

test "dialect detection ignores keywords inside comments" {
    const mysql_with_restrict =
        \\CREATE TABLE t (id int primary key, name varchar(10), KEY idx_name (name));
        \\-- RESTRICT mentioned here
    ;
    try std.testing.expectEqual(codegen.Dialect.mysql, detectSqlDialect(std.testing.allocator, mysql_with_restrict));
}

test "dialect detection does not substring-match identifiers" {
    // "RESTRICT" as an identifier must not count as STRICT; "bitmask" must
    // not count as BIT.
    try std.testing.expectEqual(codegen.Dialect.mssql, detectSqlDialect(std.testing.allocator, "CREATE TABLE t (x DATETIME2, bitmask INT)"));
    try std.testing.expectEqual(codegen.Dialect.mysql, detectSqlDialect(std.testing.allocator, "CREATE TABLE t (restrict_col INT)"));
}

test "block comment contents do not score" {
    try std.testing.expectEqual(codegen.Dialect.mysql, detectSqlDialect(std.testing.allocator, "CREATE TABLE t (a INT /* AUTOINCREMENT STRICT bytea */);"));
}

test "dialect detection still recognizes real signals" {
    try std.testing.expectEqual(codegen.Dialect.sqlite, detectSqlDialect(std.testing.allocator, "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)"));
    try std.testing.expectEqual(codegen.Dialect.pg, detectSqlDialect(std.testing.allocator, "CREATE TABLE t (id bigserial);\nCOMMENT ON TABLE t IS 'x'"));
    try std.testing.expectEqual(codegen.Dialect.db2, detectSqlDialect(std.testing.allocator, "CREATE TABLE t (id INTEGER GENERATED ALWAYS AS IDENTITY)"));
}
