const std = @import("std");
const typed_ast = @import("../types/typed_ast.zig");
const sql_type_mod = @import("../types/sql_type.zig");
const utils = @import("../utils.zig");
const version = @import("../version.zig");
const common = @import("common.zig");
const Writer = std.Io.Writer;
const Dialect = @import("../dialect/enum.zig").Dialect;

// ─── GraphQL Generator ─────────────────────────────────────────
// Produces GraphQL type definitions from TypedAst.
// Output: object types, input types, enum types, Query and Mutation types.
//
// Architecture: TypedAst → GraphQL SDL
//   Each table → object type + input type + Query fields + Mutation fields
//   Each enum column → GraphQL enum type
//   Each view → read-only object type (no mutations)
//   Comments → descriptions (triple-quoted)
//
// Type mapping:
//   int/smallint → Int
//   bigint/serial → String (no Int64 in GraphQL)
//   decimal → Float
//   varchar/text/blob/uuid/inet → String
//   datetime/timestamptz/date → DateTime (custom scalar)
//   boolean → Boolean
//   json/jsonb → JSON (custom scalar)
//   enum_values → generated enum type

pub fn generate(alloc: std.mem.Allocator, typed: typed_ast.TypedAst, _: Dialect) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    // ── Schema header ──
    try w.writeAll("# Generated by rune ");
    try utils.jsonEscapeString(w, version.VERSION);
    try w.writeAll("\n# Do not edit manually.\n\n");

    // ── Custom scalars ──
    var has_datetime = false;
    var has_json = false;
    for (typed.tables) |table| {
        for (table.columns) |col| {
            if (col.flags.is_datetime) has_datetime = true;
            if (col.sql_type == .json or col.sql_type == .jsonb) has_json = true;
        }
    }
    if (has_datetime) {
        try w.writeAll("scalar DateTime\n\n");
    }
    if (has_json) {
        try w.writeAll("scalar JSON\n\n");
    }

    // ── Enum types (from enum columns) ──
    var has_enums = false;
    for (typed.tables) |table| {
        for (table.columns) |col| {
            if (col.flags.is_enum and col.enum_values.len > 0) {
                has_enums = true;
                try writeEnumType(w, col);
            }
        }
    }
    if (has_enums) try w.writeAll("\n");

    // ── Object types (tables) ──
    for (typed.tables, 0..) |table, ti| {
        if (ti > 0) try w.writeAll("\n");
        try writeObjectType(w, table, alloc);
    }

    // ── Read-only types (views) ──
    for (typed.views, 0..) |view, vi| {
        if (typed.tables.len > 0 or vi > 0) try w.writeAll("\n");
        try writeViewType(w, view);
    }

    // ── Input types ──
    if (typed.tables.len > 0) {
        try w.writeAll("\n");
        for (typed.tables, 0..) |table, ti| {
            if (ti > 0) try w.writeAll("\n");
            try writeInputType(w, table, alloc);
        }
    }

    // ── Query type ──
    if (typed.tables.len > 0 or typed.views.len > 0) {
        try w.writeAll("\ntype Query {\n");
        for (typed.tables) |table| {
            try w.print("  \"\"\"Fetch a {s} by ID.\"\"\"\n", .{table.name});
            try w.print("  {s}(id: ID!): {s}\n", .{ try common.toCamelSingular(alloc, table.name), table.name });
            try w.print("  \"\"\"List all {s} records.\"\"\"\n", .{table.name});
            try w.print("  {s}List(limit: Int, offset: Int): [{s}!]!\n", .{ table.name, table.name });
        }
        for (typed.views) |view| {
            try w.print("  \"\"\"Fetch from view {s}.\"\"\"\n", .{view.name});
            try w.print("  {s}: [{s}!]!\n", .{ view.name, view.name });
        }
        try w.writeAll("}\n");
    }

    // ── Mutation type ──
    if (typed.tables.len > 0) {
        try w.writeAll("\ntype Mutation {\n");
        for (typed.tables) |table| {
            try w.print("  \"\"\"Create a new {s}.\"\"\"\n", .{table.name});
            try w.writeAll("  create");
            try writePascalSingular(alloc, w, table.name);
            try w.print("(input: {s}Input!): ", .{table.name});
            try writePascalSingular(alloc, w, table.name);
            try w.writeAll("!\n");

            try w.print("  \"\"\"Update an existing {s}.\"\"\"\n", .{table.name});
            try w.writeAll("  update");
            try writePascalSingular(alloc, w, table.name);
            try w.print("(id: ID!, input: {s}Input!): ", .{table.name});
            try writePascalSingular(alloc, w, table.name);
            try w.writeAll("!\n");

            try w.print("  \"\"\"Delete a {s}.\"\"\"\n", .{table.name});
            try w.writeAll("  delete");
            try writePascalSingular(alloc, w, table.name);
            try w.writeAll("(id: ID!): Boolean!\n");
        }
        try w.writeAll("}\n");
    }

    try w.flush();
    return try aw.toOwnedSlice();
}

// ─── Enum Type ─────────────────────────────────────────────────

fn writeEnumType(w: *Writer, col: typed_ast.TypedColumn) !void {
    try w.print("enum {s}Type {{\n", .{col.name});
    for (col.enum_values) |val| {
        try w.print("  {s}\n", .{val});
    }
    try w.writeAll("}\n");
}

// ─── Object Type (table) ──────────────────────────────────────

fn writeObjectType(w: *Writer, table: typed_ast.TypedTable, alloc: std.mem.Allocator) !void {
    // Description from comment
    if (table.comment) |c| {
        if (c.len > 0) {
            try w.writeAll("\"\"\"\n");
            try w.writeAll(c);
            try w.writeAll("\n\"\"\"\n");
        }
    }
    try w.print("type {s} {{\n", .{table.name});

    for (table.columns) |col| {
        try writeField(w, col, table, alloc);
    }

    // FK relation fields (object reference, not scalar)
    for (table.fks) |fk| {
        if (fk.fields.len == 1) {
            try w.print("  \"\"\"Reference to {s}\"\"\"\n", .{fk.ref_table});
            try w.print("  {s}: {s}\n", .{ try common.toCamelSingular(alloc, fk.ref_table), fk.ref_table });
        }
    }

    try w.writeAll("}\n");
}

// ─── Read-only Type (view) ────────────────────────────────────

fn writeViewType(w: *Writer, view: typed_ast.TypedView) !void {
    if (view.comment) |c| {
        if (c.len > 0) {
            try w.writeAll("\"\"\"\n");
            try w.writeAll(c);
            try w.writeAll("\n\"\"\"\n");
        }
    }
    try w.print("type {s} {{\n", .{view.name});
    try w.writeAll("  # Read-only view — columns derived from the SQL query\n");
    try w.writeAll("}\n");
}

// ─── Input Type (table) ───────────────────────────────────────

fn writeInputType(w: *Writer, table: typed_ast.TypedTable, alloc: std.mem.Allocator) !void {
    try w.print("input {s}Input {{\n", .{table.name});

    for (table.columns) |col| {
        // Skip auto-generated fields
        if (col.flags.primary_key and col.flags.auto_increment) continue;
        if (col.flags.has_timestamp_default) continue;
        if (col.flags.is_virtual) continue;
        try writeInputField(w, col, alloc);
    }

    try w.writeAll("}\n");
}

// ─── Field Writer (object type) ───────────────────────────────

fn writeField(w: *Writer, col: typed_ast.TypedColumn, table: typed_ast.TypedTable, alloc: std.mem.Allocator) !void {
    // Description from comment
    if (col.comment) |c| {
        if (c.len > 0) {
            try w.print("  \"\"\"{s}\"\"\"\n", .{c});
        }
    }

    const nullable_suffix = if (col.flags.nullable or col.flags.primary_key) "" else "!";
    const base_type = try mapType(col, table, alloc);

    try w.print("  {s}: {s}{s}\n", .{ col.name, base_type, nullable_suffix });
}

// ─── Input Field Writer ───────────────────────────────────────

fn writeInputField(w: *Writer, col: typed_ast.TypedColumn, alloc: std.mem.Allocator) !void {
    if (col.comment) |c| {
        if (c.len > 0) {
            try w.print("  \"\"\"{s}\"\"\"\n", .{c});
        }
    }
    const nullable_suffix = if (col.flags.nullable) "" else "!";
    const base_type = try mapType(col, null, alloc);
    try w.print("  {s}: {s}{s}\n", .{ col.name, base_type, nullable_suffix });
}

// ─── Type Mapping ──────────────────────────────────────────────

fn mapType(col: typed_ast.TypedColumn, table: ?typed_ast.TypedTable, alloc: std.mem.Allocator) ![]const u8 {
    // Primary key named "id" → ID scalar
    if (col.flags.primary_key) {
        if (std.mem.eql(u8, col.name, "id")) return "ID";
    }
    // FK column → Int (foreign key reference)
    if (table) |t| {
        for (t.fks) |fk| {
            if (fk.fields.len == 1 and std.mem.eql(u8, fk.fields[0], col.name)) {
                return "Int";
            }
        }
    }
    if (col.flags.is_enum) {
        // Return "{col_name}Type" — allocated so callers don't need static buffers.
        const suffix = "Type";
        const buf = try alloc.alloc(u8, col.name.len + suffix.len);
        @memcpy(buf[0..col.name.len], col.name);
        @memcpy(buf[col.name.len..], suffix);
        return buf;
    }
    return switch (col.sql_type) {
        .int, .smallint => "Int",
        .bigint, .serial => "String",
        .decimal => "Float",
        .varchar, .text, .blob, .uuid, .inet, .passthrough, .raw_sql => "String",
        .datetime, .timestamptz, .date => "DateTime",
        .boolean => "Boolean",
        .json, .jsonb => "JSON",
        .enum_values => "String",
    };
}

// ─── Name Helpers ──────────────────────────────────────────────

/// Write PascalCase singular form directly to writer. Avoids allocation.
fn writePascalSingular(alloc: std.mem.Allocator, w: *Writer, name: []const u8) !void {
    const singular = try common.toCamelSingular(alloc, name);
    if (singular.len == 0) return;
    try w.writeByte(std.ascii.toUpper(singular[0]));
    if (singular.len > 1) {
        try w.writeAll(singular[1..]);
    }
}
