const std = @import("std");
const testing = std.testing;
const pydantic = @import("pydantic.zig");
const typed_ast = @import("../types/typed_ast.zig");
const ast_mod = @import("../types/ast.zig");
const dialect_enum = @import("../dialect/enum.zig");

const Dialect = dialect_enum.Dialect;
const TypedAst = typed_ast.TypedAst;
const TypedTable = typed_ast.TypedTable;
const TypedColumn = typed_ast.TypedColumn;

const ct = @import("common_test.zig");
const makeTestColumn = ct.makeTestColumnWithFlags;
const makeTestTable = ct.makeTestTable;
const makeTestAst = ct.makeTestAstWithName;

// ─── Tests ────────────────────────────────────────────────────

test "basic type mapping: int, string, boolean" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();
    const cols = [_]TypedColumn{
        makeTestColumn("id", .int, .{ .primary_key = true, .auto_increment = true }),
        makeTestColumn("name", .{ .varchar = 255 }, .{}),
        makeTestColumn("active", .boolean, .{}),
        makeTestColumn("score", .{ .decimal = .{ .precision = 10, .scale = 2 } }, .{}),
    };
    const tables = [_]TypedTable{makeTestTable("items", &cols)};
    const ast = makeTestAst(null, &tables);

    const result = try pydantic.generate(alloc, ast, .mysql);

    try testing.expect(std.mem.indexOf(u8, result, "class Items(BaseModel):") != null);
    try testing.expect(std.mem.indexOf(u8, result, "id: int") != null);
    try testing.expect(std.mem.indexOf(u8, result, "name: str") != null);
    try testing.expect(std.mem.indexOf(u8, result, "active: bool") != null);
    try testing.expect(std.mem.indexOf(u8, result, "score: Decimal") != null);
}

test "nullable field becomes Optional with default None" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();
    const cols = [_]TypedColumn{
        makeTestColumn("id", .int, .{ .primary_key = true, .auto_increment = true }),
        makeTestColumn("bio", .text, .{ .nullable = true }),
    };
    const tables = [_]TypedTable{makeTestTable("users", &cols)};
    const ast = makeTestAst(null, &tables);

    const result = try pydantic.generate(alloc, ast, .mysql);

    // Nullable (non-pk) text → Optional[str] = None
    try testing.expect(std.mem.indexOf(u8, result, "bio: Optional[str] = None") != null);
    // Primary key id remains non-optional int
    try testing.expect(std.mem.indexOf(u8, result, "id: int") != null);
}

test "generated header references rune version" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();
    const tables = [_]TypedTable{};
    const ast = makeTestAst(null, &tables);

    const result = try pydantic.generate(alloc, ast, .pg);

    try testing.expect(std.mem.indexOf(u8, result, "# Generated by rune") != null);
    try testing.expect(std.mem.indexOf(u8, result, "from pydantic import BaseModel") != null);
}
