const std = @import("std");
const typed_ast = @import("../types/typed_ast.zig");
const utils = @import("../utils.zig");
const version = @import("../version.zig");
const Writer = std.Io.Writer;
const Dialect = @import("../dialect/enum.zig").Dialect;

// ─── Pydantic Generator ───────────────────────────────────────
// Produces Pydantic v2 data models from TypedAst.
// Output: `BaseModel` subclasses, one per table (plus read-only view models).
//
// Architecture: TypedAst → Python (Pydantic v2)
//   Each table      → `class <Name>(BaseModel)` with typed fields
//   Each view       → read-only `class <Name>View(BaseModel)` placeholder
//   Nullable column → `Optional[<T>] = None`
//   Primary key `id` → `int`
//
// Type mapping:
//   int/smallint/bigint/serial → int
//   decimal                    → Decimal
//   varchar/text/blob/uuid/inet/raw_sql/passthrough → str
//   datetime/timestamptz       → datetime
//   date                       → date
//   boolean                    → bool
//   json/jsonb                 → Any
//   enum_values                → str

pub fn generate(alloc: std.mem.Allocator, typed: typed_ast.TypedAst, _: Dialect) ![]const u8 {
    var aw = std.Io.Writer.Allocating.init(alloc);
    const w = &aw.writer;

    // ── Header ──
    try w.writeAll("# Generated by rune ");
    try utils.jsonEscapeString(w, version.VERSION);
    try w.writeAll("\n# Do not edit manually.\n\n");

    // ── Imports ──
    try w.writeAll("from typing import Optional, List, Any\n");
    try w.writeAll("from datetime import datetime, date\n");
    try w.writeAll("from decimal import Decimal\n");
    try w.writeAll("from pydantic import BaseModel, Field\n\n");

    // ── Models (tables) ──
    for (typed.tables, 0..) |table, ti| {
        if (ti > 0) try w.writeAll("\n");
        try writeModel(w, table, alloc);
    }

    // ── Read-only view models ──
    for (typed.views, 0..) |view, vi| {
        if (typed.tables.len > 0 or vi > 0) try w.writeAll("\n");
        try writeViewModel(w, view, alloc);
    }

    try w.flush();
    return try aw.toOwnedSlice();
}

// ─── Model (table) ────────────────────────────────────────────

fn writeModel(w: *Writer, table: typed_ast.TypedTable, alloc: std.mem.Allocator) !void {
    try w.writeAll("class ");
    try writePascalCase(w, table.name);
    try w.writeAll("(BaseModel):\n");

    // Class-level docstring (Rune `+` doc / `:` comment), emitted as the
    // first statement of the class body so it is a valid Python docstring.
    if (table.doc) |d| {
        if (d.len > 0) try w.print("    \"\"\"{s}\"\"\"\n", .{d});
    } else if (table.comment) |c| {
        if (c.len > 0) try w.print("    # {s}\n", .{c});
    }

    if (table.columns.len == 0) {
        try w.writeAll("    pass\n");
        return;
    }

    for (table.columns) |col| {
        try writeField(w, col, alloc);
    }
}

// ─── View model ───────────────────────────────────────────────

fn writeViewModel(w: *Writer, view: typed_ast.TypedView, alloc: std.mem.Allocator) !void {
    _ = alloc;
    if (view.doc) |d| {
        if (d.len > 0) try w.print("    \"\"\"{s}\"\"\"\n", .{d});
    } else if (view.comment) |c| {
        if (c.len > 0) try w.print("    # {s}\n", .{c});
    }

    try w.writeAll("class ");
    try writePascalCase(w, view.name);
    try w.writeAll("View(BaseModel):\n");
    try w.writeAll("    # Read-only view — columns derived from the SQL query\n");
    try w.writeAll("    pass\n");
}

// ─── Field Writer ─────────────────────────────────────────────

fn writeField(w: *Writer, col: typed_ast.TypedColumn, alloc: std.mem.Allocator) !void {
    _ = alloc;
    if (col.doc) |d| {
        if (d.len > 0) try w.print("    # {s}\n", .{d});
    } else if (col.comment) |c| {
        if (c.len > 0) try w.print("    # {s}\n", .{c});
    }

    const t = mapType(col);
    const optional = col.flags.nullable and !col.flags.primary_key;
    if (optional) {
        try w.print("    {s}: Optional[{s}] = None\n", .{ col.name, t });
    } else {
        try w.print("    {s}: {s}\n", .{ col.name, t });
    }
}

// ─── Type Mapping ─────────────────────────────────────────────

fn mapType(col: typed_ast.TypedColumn) []const u8 {
    // Primary key named "id" → int
    if (col.flags.primary_key and std.mem.eql(u8, col.name, "id")) return "int";

    return switch (col.sql_type) {
        .int, .smallint, .bigint, .serial => "int",
        .decimal => "Decimal",
        .varchar, .text, .blob, .uuid, .inet, .passthrough, .raw_sql => "str",
        .datetime, .timestamptz => "datetime",
        .date => "date",
        .boolean => "bool",
        .json, .jsonb => "Any",
        .enum_values => "str",
    };
}

// ─── Name Helper ──────────────────────────────────────────────

/// Write PascalCase form of a (snake_case) name directly to the writer.
fn writePascalCase(w: *Writer, name: []const u8) !void {
    var capitalize_next = true;
    for (name) |c| {
        if (c == '_' or c == '-' or c == ' ') {
            capitalize_next = true;
            continue;
        }
        if (capitalize_next) {
            try w.writeByte(std.ascii.toUpper(c));
            capitalize_next = false;
        } else {
            try w.writeByte(c);
        }
    }
}
