const std = @import("std");
const testing = std.testing;

// ─── Golden Test Utilities ──────────────────────────────────────
// Shared utilities for golden test comparison.
// Used by both Zig unit tests and shell-based golden test runners.
//
// Golden tests themselves run via shell scripts (tests/test*.sh)
// which handle subprocess spawning and cross-platform compatibility.
// This module provides the comparison logic for potential future
// Zig-native golden test integration.

/// Strip version strings from output for version-resilient comparison.
/// Handles SQL version comments and JSON version fields.
pub fn stripVersion(alloc: std.mem.Allocator, output: []const u8) ![]const u8 {
    var result = try std.ArrayList(u8).initCapacity(alloc, output.len);
    var lines = std.mem.splitScalar(u8, output, '\n');
    var first = true;
    while (lines.next()) |line| {
        const trimmed = std.mem.trimStart(u8, line, " ");
        // Skip SQL version comments: "-- version: rune X.Y.Z"
        if (std.mem.startsWith(u8, trimmed, "-- version: rune")) continue;
        // Skip JSON version fields: "version": "..."
        if (std.mem.indexOf(u8, line, "\"version\"") != null) continue;
        if (!first) try result.append(alloc, '\n');
        try result.appendSlice(alloc, line);
        first = false;
    }
    return try result.toOwnedSlice(alloc);
}

/// Compare two strings, ignoring trailing whitespace differences.
pub fn compareOutput(actual: []const u8, expected: []const u8) bool {
    const a = std.mem.trimEnd(u8, actual, &.{ '\n', '\r', ' ', '\t' });
    const b = std.mem.trimEnd(u8, expected, &.{ '\n', '\r', ' ', '\t' });
    return std.mem.eql(u8, a, b);
}

/// Golden test result for structured reporting.
pub const GoldenResult = struct {
    passed: bool,
    test_name: []const u8,
    diff: ?[]const u8 = null,

    pub fn deinit(self: GoldenResult, alloc: std.mem.Allocator) void {
        if (self.diff) |d| alloc.free(d);
    }
};

// ─── Tests ──────────────────────────────────────────────────────

test "stripVersion: SQL version comment" {
    const input = "-- version: rune 0.119.0\nCREATE TABLE t (id INT);\n";
    const result = try stripVersion(testing.allocator, input);
    defer testing.allocator.free(result);
    try testing.expectEqualStrings("CREATE TABLE t (id INT);\n", result);
}

test "stripVersion: multiple lines" {
    const input = "-- version: rune 0.119.0\n-- Generated by rune\nCREATE TABLE t (id INT);\n";
    const result = try stripVersion(testing.allocator, input);
    defer testing.allocator.free(result);
    try testing.expectEqualStrings("-- Generated by rune\nCREATE TABLE t (id INT);\n", result);
}

test "stripVersion: JSON version" {
    const input = "{\n  \"version\": \"0.119.0\",\n  \"tables\": 1\n}\n";
    const result = try stripVersion(testing.allocator, input);
    defer testing.allocator.free(result);
    // Note: stripVersion removes the version line entirely (no blank line left)
    try testing.expect(compareOutput(result, "{\n  \"tables\": 1\n}\n"));
}

test "stripVersion: no version" {
    const input = "CREATE TABLE t (id INT);\n";
    const result = try stripVersion(testing.allocator, input);
    defer testing.allocator.free(result);
    try testing.expectEqualStrings("CREATE TABLE t (id INT);\n", result);
}

test "compareOutput: identical" {
    try testing.expect(compareOutput("hello\n", "hello\n"));
}

test "compareOutput: trailing newline diff" {
    try testing.expect(compareOutput("hello\n", "hello"));
}

test "compareOutput: trailing whitespace diff" {
    try testing.expect(compareOutput("hello  \n", "hello\n"));
}

test "compareOutput: actual difference" {
    try testing.expect(!compareOutput("hello", "world"));
}
