// ─── Dialect Enum ───────────────────────────────────────────────
// Single source of truth for supported SQL dialects.
// Imported by: type_map, dialect, sql_parser_common, codegen, typed_ast, cli, bench.

const std = @import("std");
const version = @import("../version.zig");

pub const Dialect = enum { mysql, pg, sqlite, mssql, oracle, db2 };

/// Parse a dialect name string into the Dialect enum.
/// Supports primary names and common aliases.
pub fn parseDialect(s: []const u8) !Dialect {
    if (std.mem.eql(u8, s, "mysql")) return .mysql;
    if (std.mem.eql(u8, s, "pg") or std.mem.eql(u8, s, "postgres")) return .pg;
    if (std.mem.eql(u8, s, "sqlite") or std.mem.eql(u8, s, "sq")) return .sqlite;
    if (std.mem.eql(u8, s, "mssql") or std.mem.eql(u8, s, "sqlserver")) return .mssql;
    if (std.mem.eql(u8, s, "oracle") or std.mem.eql(u8, s, "ora")) return .oracle;
    if (std.mem.eql(u8, s, "db2") or std.mem.eql(u8, s, "idb2")) return .db2;
    return error.UnknownDialect;
}

/// Write the standard "Generated by rune" SQL header comment.
pub fn writeHeader(w: anytype, dialect: Dialect) !void {
    try w.print("-- Generated by rune {s} [{s}]\n\n", .{ version.VERSION, @tagName(dialect) });
}

/// Return the header as an allocated string (for streaming codegen).
pub fn allocHeader(alloc: std.mem.Allocator, dialect: Dialect) ![]const u8 {
    return std.fmt.allocPrint(alloc, "-- Generated by rune {s} [{s}]\n\n", .{ version.VERSION, @tagName(dialect) });
}

/// Write a migration/rollback header comment.
pub fn writeMigrationHeader(w: anytype, suffix: []const u8) !void {
    try w.print("-- Generated by rune {s} {s}\n\n", .{ version.VERSION, suffix });
}
