const std = @import("std");
const testing = std.testing;
const enum_mod = @import("enum.zig");
const Dialect = enum_mod.Dialect;

test "parseDialect: primary names" {
    try testing.expectEqual(Dialect.mysql, try enum_mod.parseDialect("mysql"));
    try testing.expectEqual(Dialect.pg, try enum_mod.parseDialect("pg"));
    try testing.expectEqual(Dialect.sqlite, try enum_mod.parseDialect("sqlite"));
    try testing.expectEqual(Dialect.mssql, try enum_mod.parseDialect("mssql"));
    try testing.expectEqual(Dialect.oracle, try enum_mod.parseDialect("oracle"));
    try testing.expectEqual(Dialect.db2, try enum_mod.parseDialect("db2"));
}

test "parseDialect: aliases" {
    try testing.expectEqual(Dialect.pg, try enum_mod.parseDialect("postgres"));
    try testing.expectEqual(Dialect.sqlite, try enum_mod.parseDialect("sq"));
    try testing.expectEqual(Dialect.mssql, try enum_mod.parseDialect("sqlserver"));
    try testing.expectEqual(Dialect.oracle, try enum_mod.parseDialect("ora"));
    try testing.expectEqual(Dialect.db2, try enum_mod.parseDialect("idb2"));
}

test "parseDialect: unknown returns error" {
    try testing.expectError(error.UnknownDialect, enum_mod.parseDialect("unknown"));
    try testing.expectError(error.UnknownDialect, enum_mod.parseDialect(""));
    try testing.expectError(error.UnknownDialect, enum_mod.parseDialect("MYSQL"));
}

test "isValidDialectName: valid names" {
    try testing.expect(enum_mod.isValidDialectName("mysql"));
    try testing.expect(enum_mod.isValidDialectName("pg"));
    try testing.expect(enum_mod.isValidDialectName("postgres"));
    try testing.expect(enum_mod.isValidDialectName("sqlite"));
    try testing.expect(enum_mod.isValidDialectName("sq"));
}

test "isValidDialectName: invalid names" {
    try testing.expect(!enum_mod.isValidDialectName("unknown"));
    try testing.expect(!enum_mod.isValidDialectName(""));
    try testing.expect(!enum_mod.isValidDialectName("MYSQL"));
}

test "VALID_NAMES_CSV contains primary names" {
    // Should contain mysql, pg, sqlite, mssql, oracle, db2
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "mysql") != null);
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "pg") != null);
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "sqlite") != null);
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "mssql") != null);
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "oracle") != null);
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "db2") != null);
    // Should NOT contain "postgres" (alias, not primary)
    try testing.expect(std.mem.indexOf(u8, enum_mod.VALID_NAMES_CSV, "postgres") == null);
}

test "ALL_NAMES has correct count" {
    // 6 primary + 5 aliases = 11 entries
    try testing.expectEqual(@as(usize, 11), enum_mod.ALL_NAMES.len);
}

test "writeMigrationHeader writes correct format" {
    var aw = std.Io.Writer.Allocating.init(testing.allocator);
    defer aw.deinit();
    try enum_mod.writeMigrationHeader(&aw.writer, "-- rollback");
    const output = aw.written();
    try testing.expect(std.mem.startsWith(u8, output, "-- Generated by rune "));
    try testing.expect(std.mem.indexOf(u8, output, "-- rollback") != null);
}
