const std = @import("std");
const dialect = @import("../dialect/dialect.zig");
const common = @import("common.zig");
const ast_mod = @import("../types/ast.zig");
const sql_type_mod = @import("../types/sql_type.zig");
const DialectBackend = dialect.DialectBackend;
const CommentResult = dialect.CommentResult;
const IndexDecl = ast_mod.IndexDecl;
const Writer = std.Io.Writer;
const SqlType = sql_type_mod.SqlType;

// ─── Oracle Backend ────────────────────────────────────────────

fn oracleQuoteIdent(w: *Writer, name: []const u8) anyerror!void {
    try w.print("\"{s}\"", .{name});
}

fn oracleEmitForeignKey(w: *Writer, fk: ast_mod.FkDecl) anyerror!void {
    try common.emitForeignKeyShared(w, fk, oracleQuoteIdent);
}

fn oracleEmitCreateView(w: *Writer, name: []const u8, query: []const u8) anyerror!void {
    try common.emitCreateViewShared(w, name, query, oracleQuoteIdent);
}

// ─── Forward Methods ─────────────────────────────────────────

fn oracleEmitIndex(w: *Writer, idx: IndexDecl, needs_comma: *bool) anyerror!void {
    try common.emitIndexWithQuote(w, idx, oracleQuoteIdent, needs_comma, "");
}

fn oracleEmitTimestampModifier(w: *Writer, _: bool) anyerror!void {
    try w.writeAll(" DEFAULT CURRENT_TIMESTAMP");
}

fn oracleEmitTableFooter(w: *Writer, _: ?[]const u8, _: ?[]const u8, _: ?[]const u8) anyerror!void {
    try w.writeAll(");\n");
}

fn oracleEmitTableComment(w: *Writer, table_name: []const u8, comment: []const u8) anyerror!void {
    try common.emitTableCommentStandalone(w, table_name, comment);
}

fn oracleEmitColumnComment(w: *Writer, table_name: []const u8, col_name: []const u8, comment: []const u8) anyerror!void {
    try common.emitColumnCommentStandalone(w, table_name, col_name, comment);
}

fn oracleEmitAutoIncrement(w: *Writer) anyerror!void {
    try w.writeAll(" GENERATED BY DEFAULT AS IDENTITY");
}

fn oracleEmitPrimaryKey(w: *Writer, _: bool) anyerror!void {
    try w.writeAll(" PRIMARY KEY");
}

fn oracleEmitInlineIndex(w: *Writer, col_name: []const u8, is_unique: bool, needs_comma: *bool) anyerror!void {
    if (needs_comma.*) try w.writeAll(",\n");
    needs_comma.* = true;
    if (is_unique) {
        try w.print("  UNIQUE INDEX \"uk_{s}\" (\"{s}\")", .{ col_name, col_name });
    } else {
        try w.print("  INDEX \"idx_{s}\" (\"{s}\")", .{ col_name, col_name });
    }
}

fn oracleEmitStandaloneIndex(_: *Writer, _: []const u8, _: IndexDecl) anyerror!void {}

fn oracleEmitInlineColumnComment(w: *Writer, comment: []const u8) anyerror!void {
    const ct = common.stripCommentPrefix(comment);
    const tr = std.mem.trim(u8, ct, " ");
    if (tr.len > 0) try w.print(" /* {s} */", .{tr});
}

fn oracleEmitInlineColumnStandaloneIndex(_: *Writer, _: []const u8, _: []const u8) anyerror!void {}

// ─── ALTER TABLE Methods ─────────────────────────────────────

fn oracleEmitAlterDropColumn(w: *Writer, col_name: []const u8) anyerror!void {
    try w.writeAll("DROP COLUMN ");
    try oracleQuoteIdent(w, col_name);
}

fn oracleEmitAlterModifyColumn(w: *Writer, col_name: []const u8) anyerror!void {
    try w.print("MODIFY (\"{s}\" ", .{col_name});
}

fn oracleEmitAlterRenameColumn(w: *Writer, old_name: []const u8, new_name: []const u8) anyerror!void {
    try w.print("RENAME COLUMN \"{s}\" TO \"{s}\"", .{ old_name, new_name });
}

fn oracleEmitAlterAddIndex(w: *Writer, table_name: []const u8, idx: IndexDecl) anyerror!void {
    try common.emitAlterAddIndexStandalone(w, table_name, idx, oracleQuoteIdent);
}

fn oracleEmitAlterDropFk(w: *Writer, fk: ast_mod.FkDecl) anyerror!void {
    try common.emitAlterDropFkShared(w, fk, "fk_", "", "_");
}

fn oracleCommentResult() CommentResult {
    return .standalone_emitted;
}

fn oracleEmitAlterTableComment(w: *Writer, table_name: []const u8, comment: []const u8) anyerror!void {
    try common.emitAlterTableCommentShared(w, table_name, comment);
}

// ─── Type Rendering ────────────────────────────────────────

const ORACLE_RENDER_TABLE = [_]dialect.RenderEntry{
    .{ .comptime_str = "NUMBER(10)" }, // int → NUMBER(10)
    .{ .comptime_str = "NUMBER(19)" }, // bigint → NUMBER(19)
    .{ .comptime_str = "NUMBER(5)" }, // smallint → NUMBER(5)
    .{ .comptime_str = "" }, // decimal — handled by oracleRenderType switch
    .{ .comptime_str = "" }, // varchar — handled by oracleRenderType switch
    .{ .comptime_str = "CLOB" }, // text → CLOB
    .{ .comptime_str = "BLOB" }, // blob → BLOB
    .{ .comptime_str = "CLOB" }, // json → CLOB
    .{ .comptime_str = "CLOB" }, // jsonb → CLOB
    .{ .comptime_str = "TIMESTAMP" }, // datetime → TIMESTAMP
    .{ .comptime_str = "DATE" }, // date → DATE
    .{ .comptime_str = "TIMESTAMP WITH TIME ZONE" }, // timestamptz
    .{ .comptime_str = "NUMBER(1)" }, // boolean → NUMBER(1)
    .{ .comptime_str = "RAW(16)" }, // uuid → RAW(16)
    .{ .comptime_str = "VARCHAR2(45)" }, // inet → VARCHAR2(45)
    .{ .comptime_str = "NUMBER(10)" }, // serial → NUMBER(10)
    .{ .comptime_str = "" }, // enum_values — handled by oracleRenderType switch
    .{ .comptime_str = "" }, // raw_sql — handled by passthrough fallback
    .{ .comptime_str = "" }, // passthrough — written from variant
};

fn oracleRenderType(w: *Writer, sql_type: SqlType) anyerror!void {
    switch (sql_type) {
        .decimal => |d| try common.emitDecimal(w, "NUMBER", d.precision, d.scale),
        .varchar => |n| try common.emitVarchar(w, "VARCHAR2", n, 255),
        .enum_values => try common.emitEnumFixedType(w, "VARCHAR2(255)"),
        else => try common.renderTypeFromTable(w, sql_type, &ORACLE_RENDER_TABLE),
    }
}

// ─── Forward Type Mapping (SS symbol → SqlType) ─────────────

fn oracleLookupSym(sym: []const u8) ?SqlType {
    return common.lookupSymDefault(&.{}, sym);
}

// ─── Generated Columns ──────────────────────────────────────

fn oracleEmitGeneratedColumn(w: *Writer, expr: []const u8, is_stored: bool) anyerror!void {
    try w.writeAll("GENERATED ALWAYS AS (");
    try w.writeAll(expr);
    try w.writeAll(") ");
    if (is_stored) {
        try w.writeAll("STORED");
    } else {
        try w.writeAll("VIRTUAL");
    }
}

// ─── Backend Instance ──────────────────────────────────────

pub const oracle_backend = DialectBackend{
    .quoteIdent = oracleQuoteIdent,
    .emitIndex = oracleEmitIndex,
    .emitTimestampModifier = oracleEmitTimestampModifier,
    .emitTableFooter = oracleEmitTableFooter,
    .emitTableComment = oracleEmitTableComment,
    .emitColumnComment = oracleEmitColumnComment,
    .emitPrimaryKey = oracleEmitPrimaryKey,
    .emitInlineIndex = oracleEmitInlineIndex,
    .emitStandaloneIndex = oracleEmitStandaloneIndex,
    .emitInlineColumnComment = oracleEmitInlineColumnComment,
    .emitEnumTypeCheck = common.emitEnumTypeCheck,
    .emitInlineColumnStandaloneIndex = oracleEmitInlineColumnStandaloneIndex,
    .emitAlterDropColumn = oracleEmitAlterDropColumn,
    .emitAlterModifyColumn = oracleEmitAlterModifyColumn,
    .emitAlterRenameColumn = oracleEmitAlterRenameColumn,
    .emitAlterAddIndex = oracleEmitAlterAddIndex,
    .emitAlterDropIndex = common.emitAlterDropIndexNoQuote,
    .emitAlterDropFk = oracleEmitAlterDropFk,
    .commentResult = oracleCommentResult,
    .emitAlterTableComment = oracleEmitAlterTableComment,
    .emitAlterEngine = common.emitAlterEngineWarning,
    .emitCreateView = oracleEmitCreateView,
    .renderType = oracleRenderType,
    .emitForeignKey = oracleEmitForeignKey,
    .emitAutoIncrement = oracleEmitAutoIncrement,
    .emitGeneratedColumn = oracleEmitGeneratedColumn,
    .lookupSym = oracleLookupSym,
    .quoteChar = '"',
    .rename_needs_column_def = false,
    .modify_needs_column_def = true,
    .modify_column_def_skips_name = true,
    .capability = .{
        .auto_increment = true,
        .standalone_comments = true,
        .schemas = true,
        .sequences = true,
        .generated_columns = true,
        .alter_drop_column = true,
    },
};
