-- Db2 types: BOOLEAN, DECIMAL, BIGINT, SMALLINT
CREATE TABLE products (
  id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) DEFAULT 0,
  quantity BIGINT DEFAULT 0,
  weight SMALLINT DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id)
);
