-- Generated by rune

CREATE DATABASE `generated_cols` CHARACTER SET utf8mb4;

CREATE TABLE `products` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL,
  `price` int NOT NULL,
  `qty` int NOT NULL DEFAULT 1,
  `total` int GENERATED ALWAYS AS (price * qty) VIRTUAL,
  `tax` int GENERATED ALWAYS AS (price * 0.1) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
