-- Oracle identity columns and foreign keys
CREATE TABLE customers (
  id NUMBER(10) NOT NULL,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(255),
  PRIMARY KEY (id)
);

CREATE TABLE orders (
  id NUMBER(10) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_id NUMBER(10) NOT NULL,
  total NUMBER(10,2) DEFAULT 0,
  status VARCHAR2(20) DEFAULT 'pending',
  PRIMARY KEY (id),
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);
